[LangOptions]
LanguageName=ChineseSimplified
LanguageID=$0804
LanguageCodePage=936
DialogFontName=Microsoft YaHei UI
DialogFontSize=9
WelcomeFontName=Microsoft YaHei UI
WelcomeFontSize=12

[Messages]
SetupAppTitle=安装
SetupWindowTitle=安装 - %1
UninstallAppTitle=卸载
InformationTitle=信息
ConfirmTitle=确认
ErrorTitle=错误
WelcomeLabel1=欢迎使用 [name] 安装向导
WelcomeLabel2=此向导将引导您完成 [name/ver] 的安装。%n%n建议在继续之前关闭所有其他应用程序。
SelectDirDesc=选择 [name] 的安装位置。
SelectDirLabel3=安装程序将把 [name] 安装到以下文件夹。
SelectDirBrowseLabel=如需安装到其他文件夹，请点击"浏览"。
DiskSpaceMBLabel=至少需要 [mb] MB 的可用磁盘空间。
DiskSpaceGBLabel=至少需要 [gb] GB 的可用磁盘空间。
CannotInstallToNetworkDrive=安装程序无法安装到网络驱动器。
CannotInstallToUNCPath=安装程序无法安装到 UNC 路径。
InvalidPath=请输入完整的驱动器路径，例如：%n%nC:\APP%n%n或 UNC 路径：%n%n\\server\share
InvalidDrive=所选驱动器或 UNC 路径不存在或无法访问。请选择其他位置。
DiskSpaceWarning=至少需要 %1 KB 的可用磁盘空间才能安装。%n%n您要继续吗？
DiskSpaceWarningTitle=磁盘空间不足
DirNameTooLong=目录名称太长。
DirDoesntExist=目录%n%n%1%n%n不存在。是否要创建该目录？
DirDoesntExistTitle=目录不存在
DirExistsTitle=目录已存在
DirExists=目录%n%n%1%n%n已存在。是否仍要安装到此目录？
InvalidDirName=文件夹名称无效。
BadDirName32=文件夹名称不能包含以下字符：%n%n%1
SelectComponentsDesc=选择安装类型：
SelectComponentsLabel2=选择需要安装的组件，然后点击"下一步"。
FullInstallation=完全安装
CompactInstallation=精简安装
CustomInstallation=自定义安装

ComponentsDiskSpaceMBLabel=当前选择至少需要 [mb] MB 的可用磁盘空间。
ComponentsDiskSpaceGBLabel=当前选择至少需要 [gb] GB 的可用磁盘空间。
ComponentSize1=%1 KB
ComponentSize2=%1 MB
SelectStartMenuFolderDesc=选择安装程序创建快捷方式的位置。
SelectStartMenuFolderLabel3=安装程序将在以下开始菜单文件夹中创建快捷方式。
SelectStartMenuFolderBrowseLabel=如需选择其他文件夹，请点击"浏览"。
MustEnterGroupName=请输入文件夹名称。
GroupNameTooLong=文件夹名称太长。
InvalidGroupName=文件夹名称无效。
BadGroupName=文件夹名称不能包含以下字符：%n%n%1
NoProgramGroupCheck2=不创建开始菜单文件夹(&D)
SelectTasksDesc=选择附加任务。
SelectTasksLabel2=选择安装程序要执行的附加任务，然后点击"下一步"。

ReadyLabel1=安装程序已准备好将 [name] 安装到您的计算机。
ReadyLabel2a=点击"安装"开始安装，或点击"上一步"修改设置。
ReadyLabel2b=点击"安装"开始安装。
ReadyMemoDir=安装位置：
ReadyMemoGroup=开始菜单文件夹：
ReadyMemoTasks=附加任务：
ReadyMemoComponents=组件：
ReadyMemoType=安装类型：
ReadyMemoUserInfo=用户信息：
PreparingDesc=安装程序正在准备安装...
PreviousInstallNotCompleted=之前的安装/卸载未完成。需要重新启动计算机才能完成。%n%n重新启动计算机后再次运行安装程序完成安装。
InstallingLabel=正在安装 [name]，请稍候...
FinishedHeadingLabel=[name] 安装完成
FinishedLabelNoIcons=[name] 已成功安装到您的计算机。
FinishedLabel=[name] 已成功安装到您的计算机。%n%n您可以通过桌面快捷方式启动程序。
ClickFinish=点击"完成"退出安装向导。
FinishedRestartLabel=要完成安装，需要重新启动计算机。%n%n是否立即重新启动？
FinishedRestartMessage=要完成安装，需要重新启动计算机。%n%n是否立即重新启动？
ShowReadmeCheck=查看自述文件
YesRadio=是，立即重新启动计算机(&Y)
NoRadio=否，稍后手动重新启动(&N)
RunEntryExec=启动 %1
RunEntryShellExec=查看 %1
ChangeDiskTitle=需要下一张磁盘
SelectDiskLabel2=请插入磁盘 %1 并点击"确定"。%n%n如果文件位于其他位置，请输入正确路径或点击"浏览"。
PathLabel=路径(&P)：
FileNotInDir2=在 "%2" 中找不到文件 "%1"。请输入正确的路径或点击"浏览"。
SelectDirectoryLabel=请指定下一张磁盘的位置。
SetupAborted=安装未完成。%n%n请修正问题后重新运行安装程序。
AbortRetryIgnoreSelectAction=选择操作
AbortRetryIgnoreCancel=取消
AbortRetryIgnoreIgnore=忽略
AbortRetryIgnoreRetry=重试
ExitSetupTitle=退出安装
ExitSetupMessage=安装尚未完成。如果现在退出，程序将不会被安装。%n%n您可以稍后再次运行安装程序完成安装。%n%n是否退出安装？
AboutSetupMenuItem=关于安装程序(&A)...
AboutSetupTitle=关于安装程序
AboutSetupMessage=%1 版本 %2%n%3%n%n%1 主页：%4
AboutSetupNote=Inno Setup 安装程序%nCopyright (C) 1997-2026 Jordan Russell. 保留所有权利。%n%nPortions Copyright (C) 2000-2026 Martijn Laan. 保留所有权利。
SetupLdrStartupMessage=此向导将安装 [name/ver]。%n%n是否继续？
SetupFileCorrupt=安装文件已损坏。请获取新的安装程序副本。
SetupFileCorruptOrWrongVer=安装文件已损坏或与本安装程序版本不兼容。请排查问题或获取新的安装程序副本。
SetupFileMissing=找不到文件 %1。请修正问题或获取新的安装程序副本。
SetupAppRunningError=安装程序检测到 %1 正在运行。%n%n请先关闭该程序，然后点击"确定"继续，或点击"取消"退出。
SetupAlreadyRunning=安装程序已在运行。
CannotContinue=安装无法继续。请点击"取消"退出。

AdminPrivilegesRequired=安装程序需要管理员权限才能继续。
PowerUserPrivilegesRequired=安装程序需要管理员或高级用户权限才能继续。
PrepareToInstallNeedsRestart=安装程序需要重新启动计算机才能继续。%n%n重新启动后，安装程序将继续。%n%n是否立即重新启动？
StatusCreateDirs=正在创建目录...
StatusExtractFiles=正在解压文件...
StatusCreateIcons=正在创建快捷方式...
StatusCreateIniEntries=正在创建 INI 条目...
StatusCreateRegistryEntries=正在创建注册表条目...
StatusRegisterFiles=正在注册文件...
StatusSavingUninstall=正在保存卸载信息...
StatusRollback=正在回滚更改...
StatusRunProgram=正在完成安装...
StatusUninstalling=正在卸载...
StatusClosingApplications=正在关闭应用程序...
StatusRestartingApplications=正在重新启动应用程序...
StatusDownloadFiles=正在下载文件...
UninstallStatusLabel=正在卸载 %1，请稍候...
UninstalledAll=%1 已成功从计算机中移除。
UninstalledMost=%1 卸载完成。%n%n某些内容无法自动删除，您可以手动删除。
UninstalledAndNeedsRestart=要完成卸载 %1，需要重新启动计算机。%n%n是否立即重新启动？
UninstallDataCorrupted="%1" 文件已损坏，无法卸载。
UninstallAppFullTitle=卸载 - %1 %2
UninstallDisplayNameMark=%1 [%2]
UninstallDisplayNameMarks=%1 [%2, %3]
UninstallDisplayNameMark32Bit=32位
UninstallDisplayNameMark64Bit=64位
UninstallDisplayNameMarkAllUsers=所有用户
UninstallDisplayNameMarkCurrentUser=当前用户
UninstallNotFound=未找到 %1 的安装信息。可能已被其他方式卸载。
UninstallOpenError=无法打开卸载日志文件 "%1"。
UninstallUnsupportedVer=卸载日志文件 "%1" 的版本不被此版本卸载程序支持。
UninstallUnknownEntry=卸载日志中存在未知条目 (%1)。
UninstallAppRunningError=%1 正在运行。请先关闭该程序，然后点击"确定"继续，或点击"取消"退出。
UninstallOnlyOnWin64=此程序只能在 64 位 Windows 上卸载。
ConfirmDeleteSharedFileTitle=删除共享文件？
ConfirmDeleteSharedFile2=系统指示以下共享文件已不再被任何程序使用。是否删除此文件？%n%n如果仍有程序在使用此文件而您将其删除，该程序可能无法正常运行。如果您不确定，请选择"否"。保留此文件是安全的。
SharedFileNameLabel=文件名：
SharedFileLocationLabel=位置：
OnlyOnThisPlatform=此程序需要在 %1 上运行。
NotOnThisPlatform=此程序无法在 %1 上运行。
OnlyOnTheseArchitectures=此程序只能在以下处理器架构的 Windows 版本上安装：%n%n%1
OnlyAdminCanUninstall=此程序只能由管理员卸载。
NoUninstallWarningTitle=文件存在
NoUninstallWarning=安装程序发现以下文件不属于 %1，将不会被删除：%n%n%2%n%n是否全部保留？
ConfirmUninstall=是否确定要完全卸载 %1 及其所有组件？
ShutdownBlockReasonInstallingApp=正在安装 %1。
ShutdownBlockReasonUninstallingApp=正在卸载 %1。
ErrorChangingAttr=无法更改文件 "%1" 的属性。%n%n%2
ErrorCreatingDir=安装程序无法创建目录 "%1"。%n%n%2
ErrorCreatingTemp=安装程序无法在临时目录中创建文件。%n%n%1
ErrorExtractionAborted=文件解压被中止。
ErrorExtractionFailed=安装程序无法解压文件。%n%n%1
ErrorExtracting=安装程序无法解压文件 "%1"。%n%n%2
ErrorCopying=安装程序无法复制文件 "%1" 到 "%2"。%n%n%3
ErrorDownloading=下载文件 "%1" 失败。%n%n%2
ErrorDownloadAborted=下载已中止。
ErrorDownloadFailed=下载失败。
ErrorDownloadSizeFailed=无法获取下载大小。
ErrorExecutingProgram=安装程序无法执行文件：%n%n%1
ErrorFunctionFailed=%1 函数调用失败。%n%n%2
ErrorFunctionFailedNoCode=%1 函数调用失败。
ErrorFunctionFailedWithMessage=%1 函数调用失败。%n%n%2%n%n%3
ErrorIniEntry=无法在文件 "%1" 中创建 INI 条目。
ErrorInternal2=内部错误：%1
ErrorOpeningReadme=无法打开自述文件。
ErrorProgress=进度回调失败：%1
ErrorReadingExistingDest=读取现有文件 "%1" 时出错。%n%n%2
ErrorReadingSource=读取源文件 "%1" 时出错。%n%n%2
ErrorRegCreateKey=无法创建注册表键：%n%n%1%n%n%2
ErrorRegOpenKey=无法打开注册表键：%n%n%1%n%n%2
ErrorRegWriteKey=无法写入注册表键：%n%n%1%n%n%2
ErrorRegisterServer=无法注册 DLL/OCX：%1%n%n%2
ErrorRegisterTypeLib=无法注册类型库：%1%n%n%2
ErrorRegSvr32Failed=RegSvr32 失败，退出代码 %1。
ErrorRenamingTemp=无法将临时文件 "%1" 重命名为 "%2"。%n%n%3
ErrorReplacingExistingFile=无法替换现有文件 "%1"。%n%n%2
ErrorRestartingComputer=安装程序无法重新启动计算机。请手动重新启动。
ErrorRestartReplace=重新启动替换失败：%1
ErrorTooManyFilesInDir=目录 "%1" 中的文件过多。
ErrorFileSize=文件 "%1" 的大小不正确。
SourceIsCorrupted=源文件已损坏。
SourceDoesntExist=源文件 "%1" 不存在。
SourceVerificationFailed=源文件验证失败。
ArchiveIncorrectPassword=密码不正确。
ArchiveIsCorrupted=压缩包已损坏。
ArchiveUnsupportedFormat=不支持的压缩包格式。
IncorrectPassword=密码不正确。
ExistingFileNewerSelectAction=选择操作
ExistingFileNewer2=目标文件比源文件更新。%n%n是否覆盖？
ExistingFileNewerOverwriteExisting=覆盖现有文件(&O)
ExistingFileNewerKeepExisting=保留现有文件(&K)
ExistingFileNewerOverwriteOrKeepAll=对所有后续文件执行相同操作(&A)
ExistingFileReadOnly2=现有文件 "%1" 是只读的。%n%n是否覆盖？
ExistingFileReadOnlyRetry=重试(&R)
ExistingFileReadOnlyKeepExisting=保留现有文件(&K)
FileExistsSelectAction=选择操作
FileExists2=文件 "%1" 已存在。%n%n是否覆盖？
FileExistsOverwriteExisting=覆盖现有文件(&O)
FileExistsKeepExisting=保留现有文件(&K)
FileExistsOverwriteOrKeepAll=对所有后续文件执行相同操作(&A)
FileAbortRetryIgnoreSkipNotRecommended=跳过此文件（不推荐）(&S)
FileAbortRetryIgnoreIgnoreNotRecommended=忽略错误并继续（不推荐）(&I)
RetryCancelSelectAction=选择操作
RetryCancelRetry=重试(&T)
RetryCancelCancel=取消
LdrCannotCreateTemp=无法创建临时文件。安装已中止。
LdrCannotExecTemp=无法执行临时目录中的文件。安装已中止。
InfoBeforeLabel=请在继续安装之前阅读以下重要信息。
InfoBeforeClickLabel=准备好继续安装后，请点击"下一步"。
InfoAfterLabel=请在继续之前阅读以下重要信息。
InfoAfterClickLabel=准备好继续后，请点击"下一步"。
LicenseLabel=请在继续安装之前阅读以下许可协议。
LicenseLabel3=请在继续安装之前阅读以下许可协议。您必须接受协议条款才能继续。
LicenseAccepted=我接受协议(&A)
LicenseNotAccepted=我不接受协议(&D)
PasswordEditLabel=密码(&P)：
PasswordLabel1=此安装程序需要密码才能继续。
PasswordLabel3=请输入密码，然后点击"下一步"。
NewFolderName=新建文件夹
BrowseDialogLabel=选择目标文件夹，然后点击"确定"。
BrowseDialogTitle=选择文件夹
WizardSelectDir=选择安装位置
WizardSelectComponents=选择组件
WizardSelectProgramGroup=选择开始菜单文件夹
WizardSelectTasks=选择附加任务
WizardInstalling=正在安装
WizardReady=准备安装
WizardLicense=许可协议
WizardPreparing=准备安装
WizardUninstalling=正在卸载
WizardUserInfo=用户信息
WizardPassword=密码
WizardInfoBefore=信息
WizardInfoAfter=信息
UserInfoDesc=请输入您的信息。
UserInfoName=用户名(&U)：
UserInfoNameRequired=必须输入用户名。
UserInfoOrg=组织(&O)：
UserInfoSerial=序列号(&S)：
SelectLanguageTitle=选择安装语言
SelectLanguageLabel=请选择安装时使用的语言：
ClickNext=点击"下一步"继续，或点击"取消"退出安装。
BeveledLabel=
WindowsVersionNotSupported=此程序不支持当前 Windows 版本。
WindowsServicePackRequired=此程序需要 %1 Service Pack %2。
WinVersionTooLowError=此程序需要 %1 %2 或更高版本。
WinVersionTooHighError=此程序无法在 %1 %2 或更高版本上运行。
PrivilegesRequiredOverrideTitle=选择安装模式
PrivilegesRequiredOverrideInstruction=选择安装模式
PrivilegesRequiredOverrideText1=%1 需要管理员权限。请选择安装模式：
PrivilegesRequiredOverrideText2=%1 不需要管理员权限。请选择安装模式：
PrivilegesRequiredOverrideAllUsers=为所有用户安装（需要管理员权限）
PrivilegesRequiredOverrideAllUsersRecommended=为所有用户安装（推荐）（需要管理员权限）
PrivilegesRequiredOverrideCurrentUser=仅为当前用户安装
PrivilegesRequiredOverrideCurrentUserRecommended=仅为当前用户安装（推荐）
CloseApplications=安装程序检测到以下应用程序正在使用需要更新的文件。请让安装程序自动关闭这些应用程序，或在安装完成后重新启动计算机。
DontCloseApplications=不要关闭应用程序
ErrorCloseApplications=安装程序无法自动关闭所有应用程序。在安装前，请手动关闭使用需要更新文件的应用程序。
ApplicationsFound=安装程序检测到以下应用程序正在使用需要更新的文件。
ApplicationsFound2=安装程序检测到以下应用程序正在使用需要更新的文件。请让安装程序自动关闭这些应用程序，或在安装完成后重新启动计算机。
StopDownload=停止下载
StopExtraction=停止解压
ExtractingLabel=正在解压文件，请稍候...
DownloadingLabel2=正在下载文件，请稍候...
VerificationFileHashIncorrect=文件哈希验证失败。
VerificationFileNameIncorrect=文件名验证失败。
VerificationFileSizeIncorrect=文件大小验证失败。
VerificationFileTagIncorrect=文件标签验证失败。
VerificationKeyNotFound=未找到验证密钥。
VerificationSignatureDoesntExist=数字签名不存在。
VerificationSignatureInvalid=数字签名无效。
LastErrorMessage=%1%n%n错误 %2：%3
InvalidParameter=函数 %1 接收到无效参数。

ButtonBack=< 上一步(&B)
ButtonNext=下一步(&N) >
ButtonInstall=安装(&I)
ButtonOK=确定
ButtonCancel=取消
ButtonYes=是(&Y)
ButtonYesToAll=全部是(&A)
ButtonNo=否(&N)
ButtonNoToAll=全部否(&O)
ButtonFinish=完成(&F)
ButtonBrowse=浏览(&R)...
ButtonWizardBrowse=浏览(&R)...
ButtonNewFolder=新建文件夹(&M)
ButtonStopDownload=停止下载(&S)
ButtonStopExtraction=停止解压(&S)

[CustomMessages]
CreateDesktopIcon=创建桌面快捷方式(&D)
CreateQuickLaunchIcon=创建快速启动栏快捷方式(&Q)
AdditionalIcons=附加快捷方式：
UninstallProgram=卸载 %1
LaunchProgram=启动 %1
