// <auto-generated>
// 由 scripts/generate-app-font.py 从 Assets/Fonts/app-font.json 生成 —— 请勿手改。
// 用途：app-font.json 缺失/损坏时 AppFonts 启动读取失败的编译期兜底镜像；
//       FontSingleSourceTests 断言其与 app-font.json 逐字段一致（防两处漂移）。
// </auto-generated>
namespace TubaWinUi3.Services;

public sealed partial class AppFontCatalog
{
    /// <summary>配置缺失/损坏时的兜底镜像（与 app-font.json 逐字段一致，由 FontSingleSourceTests 钉住）。</summary>
    public static AppFontCatalog Fallback { get; } = new()
    {
        UiStackSuffix = "'Segoe UI Variable', 'Segoe UI', 'Microsoft YaHei', system-ui, -apple-system, sans-serif",
        MonoStack = "'Maple Mono CN', 'Cascadia Mono', 'Consolas', 'Courier New', ui-monospace, monospace",
        Mono = new AppFontMonoSpec
        {
            FamilyName = "Maple Mono CN",
            RegularFileName = "MapleMono-CN-Regular.ttf",
            BoldFileName = "MapleMono-CN-Bold.ttf",
            LicenseFileName = "OFL.txt",
        },
        Choices = new List<AppFontSpec>
        {
            new AppFontSpec
            {
                Id = "sarasa",
                DisplayName = "更纱黑体 Sarasa UI SC",
                FamilyName = "Sarasa UI SC",
                RegularFileName = "SarasaUiSC-Regular.ttf",
                BoldFileName = "SarasaUiSC-Bold.ttf",
                LicenseFileName = "SarasaUiSC-OFL.txt",
                Attribution = new AppFontSpec.FontAttribution
                {
                    Author = "Renzhi Li（Belleve Invis）",
                    Url = "https://github.com/be5invis/Sarasa-Gothic",
                    LicenseText = "SIL OFL 1.1 开源许可（随包附许可原文）",
                },
            },
            new AppFontSpec
            {
                Id = "noto",
                DisplayName = "Noto Sans SC",
                FamilyName = "Noto Sans SC",
                RegularFileName = "NotoSansSC-Regular.otf",
                BoldFileName = "NotoSansSC-Bold.otf",
                LicenseFileName = "NotoSansSC-OFL.txt",
                Attribution = new AppFontSpec.FontAttribution
                {
                    Author = "Google（Noto 项目）",
                    Url = "https://fonts.google.com/noto/specimen/Noto+Sans+SC",
                    LicenseText = "SIL OFL 1.1 开源许可（随包附许可原文）",
                },
            },
            new AppFontSpec
            {
                Id = "harmony",
                DisplayName = "HarmonyOS Sans SC",
                FamilyName = "HarmonyOS Sans SC",
                RegularFileName = "HarmonyOS_Sans_SC_Regular.ttf",
                BoldFileName = "HarmonyOS_Sans_SC_Bold.ttf",
                LicenseFileName = "HarmonyOS-Sans-LICENSE.txt",
                Attribution = new AppFontSpec.FontAttribution
                {
                    Author = "华为终端有限公司（HarmonyOS Sans）",
                    Url = "https://developer.huawei.com/images/download/general/HarmonyOS-Sans.zip",
                    LicenseText = "HarmonyOS Sans Fonts License Agreement（华为自有许可，非开源；随包附协议原文）",
                },
            },
        },
    };
}
