namespace TubaWinUi3.Services;

/// <summary>
/// 分类显示名映射：物理分类名（中文，永远是数据键）→ 资源键。
/// 仅用于显示层；Tag、CategoryOrder、CategoryGlyph_* 设置键一律保持原始中文名。
/// </summary>
internal static class CategoryDisplayNames
{
    /// <summary>Tools/ 目录下的外部工具分类。</summary>
    private static readonly Dictionary<string, string> ToolCategories = new(StringComparer.OrdinalIgnoreCase)
    {
        ["处理器工具"] = "Category_Processor",
        ["显卡工具"] = "Category_Graphics",
        ["显示器工具"] = "Category_Display",
        ["硬盘工具"] = "Category_Storage",
        ["内存工具"] = "Category_Memory",
        ["外设工具"] = "Category_Peripherals",
        ["游戏工具"] = "Category_Gaming",
        ["声卡工具"] = "Category_Audio",
        ["网卡工具"] = "Category_Network",
        ["烤鸡工具"] = "Category_StressTest",
        ["综合检测"] = "Category_GeneralCheck",
        ["综合工具"] = "Category_General",
        ["其他工具"] = "Category_Other",
    };

    /// <summary>内置工具分类（IBuiltinTool.Category）。</summary>
    private static readonly Dictionary<string, string> BuiltinCategories = new(StringComparer.OrdinalIgnoreCase)
    {
        ["系统工具"] = "Category_Builtin_System",
        ["硬件工具"] = "Category_Builtin_Hardware",
        ["网络工具"] = "Category_Builtin_Network",
        ["游戏工具"] = "Category_Builtin_Gaming",
        ["实用工具"] = "Category_Builtin_Utility",
    };

    /// <summary>工具标签（tools.json 的 tags，恒中文，数据键）→ 资源键；仅显示层使用。</summary>
    private static readonly Dictionary<string, string> Tags = new(StringComparer.OrdinalIgnoreCase)
    {
        ["AMD"] = "Tag_Amd",
        ["BIOS刷写"] = "Tag_BiosFlash",
        ["CPU"] = "Tag_Cpu",
        ["DPC"] = "Tag_Dpc",
        ["DirectX"] = "Tag_DirectX",
        ["GIF录制"] = "Tag_GifRec",
        ["GPT"] = "Tag_Gpt",
        ["GPU"] = "Tag_Gpu",
        ["HDR"] = "Tag_Hdr",
        ["ISO"] = "Tag_Iso",
        ["Intel"] = "Tag_Intel",
        ["MBR"] = "Tag_Mbr",
        ["NVIDIA"] = "Tag_Nvidia",
        ["OSD"] = "Tag_Osd",
        ["SMART"] = "Tag_Smart",
        ["SPD"] = "Tag_Spd",
        ["SSD"] = "Tag_Ssd",
        ["USB"] = "Tag_Usb",
        ["U盘"] = "Tag_UsbDrive",
        ["U盘启动"] = "Tag_UsbBoot",
        ["VR"] = "Tag_Vr",
        ["x64"] = "Tag_X64",
        ["三星"] = "Tag_Samsung",
        ["主板"] = "Tag_Motherboard",
        ["传感器"] = "Tag_Sensors",
        ["修复"] = "Tag_Repair",
        ["健康检测"] = "Tag_HealthCheck",
        ["光盘"] = "Tag_OpticalDisc",
        ["其他"] = "Tag_Other",
        ["内存"] = "Tag_Memory",
        ["内存分析"] = "Tag_MemoryAnalysis",
        ["分区"] = "Tag_Partitioning",
        ["刷新率测试"] = "Tag_RefreshRateTest",
        ["刻录"] = "Tag_DiscBurning",
        ["功耗控制"] = "Tag_PowerControl",
        ["压力测试"] = "Tag_StressTest",
        ["启动项"] = "Tag_StartupItems",
        ["回报率"] = "Tag_ReportRate",
        ["在线测试"] = "Tag_OnlineTest",
        ["坏点测试"] = "Tag_DeadPixelTest",
        ["坏道"] = "Tag_BadSectors",
        ["坏道检测"] = "Tag_BadSectorScan",
        ["基准测试"] = "Tag_Benchmark",
        ["外设"] = "Tag_Peripherals",
        ["安全"] = "Tag_Security",
        ["屏幕检测"] = "Tag_ScreenTest",
        ["帧率监控"] = "Tag_FpsMonitor",
        ["底层读写"] = "Tag_LowLevelIo",
        ["延迟检测"] = "Tag_LatencyCheck",
        ["延迟测试"] = "Tag_LatencyTest",
        ["开源"] = "Tag_OpenSource",
        ["引导扇区"] = "Tag_BootSector",
        ["微软官方"] = "Tag_MsOfficial",
        ["性能测试"] = "Tag_PerformanceTest",
        ["扫描"] = "Tag_Scan",
        ["拓扑"] = "Tag_Topology",
        ["按键映射"] = "Tag_KeyMapping",
        ["数据恢复"] = "Tag_DataRecovery",
        ["文件复制"] = "Tag_FileCopy",
        ["文件搜索"] = "Tag_FileSearch",
        ["文件管理"] = "Tag_FileMgmt",
        ["时序"] = "Tag_Timings",
        ["显卡"] = "Tag_Graphics",
        ["显示器"] = "Tag_Display",
        ["杀毒"] = "Tag_Antivirus",
        ["校准"] = "Tag_Calibration",
        ["格式化"] = "Tag_Formatting",
        ["桌面管理"] = "Tag_DesktopMgmt",
        ["温度"] = "Tag_Temperature",
        ["温度监控"] = "Tag_TempMonitoring",
        ["温控"] = "Tag_ThermalControl",
        ["渲染"] = "Tag_Rendering",
        ["游戏"] = "Tag_Gaming",
        ["烤机"] = "Tag_BurnIn",
        ["烤鸡"] = "Tag_BurnIn2",
        ["电池"] = "Tag_Battery",
        ["电源测试"] = "Tag_PowerTest",
        ["监控"] = "Tag_Monitoring",
        ["真伪检测"] = "Tag_AuthenticityCheck",
        ["硬件信息"] = "Tag_HardwareInfo",
        ["硬件检测"] = "Tag_HardwareCheck",
        ["硬盘"] = "Tag_Disk",
        ["碎片整理"] = "Tag_Defrag",
        ["稳定性"] = "Tag_Stability",
        ["稳定性测试"] = "Tag_StabilityTest",
        ["空间分析"] = "Tag_SpaceAnalysis",
        ["精简"] = "Tag_Slimming",
        ["系统"] = "Tag_System",
        ["系统优化"] = "Tag_SystemTweaks",
        ["系统增强"] = "Tag_SystemEnhancement",
        ["系统工具"] = "Tag_SystemTools",
        ["系统诊断"] = "Tag_SystemDiagnostics",
        ["系统镜像"] = "Tag_SystemImage",
        ["综合检测"] = "Tag_Diagnostics",
        ["色域检测"] = "Tag_ColorGamutTest",
        ["蓝屏分析"] = "Tag_BsodAnalysis",
        ["虚拟磁盘"] = "Tag_VirtualDisk",
        ["表面扫描"] = "Tag_SurfaceScan",
        ["解码检测"] = "Tag_DecodeCheck",
        ["设备管理"] = "Tag_DeviceMgmt",
        ["诊断"] = "Tag_Diagnose",
        ["调教"] = "Tag_Tuning",
        ["调试"] = "Tag_Debugging",
        ["超频"] = "Tag_Overclocking",
        ["跑分"] = "Tag_Benchmarking",
        ["软件卸载"] = "Tag_SoftwareUninstall",
        ["软件迁移"] = "Tag_SoftwareMigration",
        ["进程监控"] = "Tag_ProcessMonitor",
        ["进程管理"] = "Tag_ProcessMgmt",
        ["速度测试"] = "Tag_SpeedTest",
        ["量产"] = "Tag_MassProduction",
        ["锐龙"] = "Tag_Ryzen",
        ["键盘"] = "Tag_Keyboard",
        ["键盘测试"] = "Tag_KeyboardTest",
        ["降频"] = "Tag_Underclocking",
        ["风扇"] = "Tag_Fan",
        ["驱动"] = "Tag_Drivers",
        ["驱动下载"] = "Tag_DriverDownload",
        ["驱动卸载"] = "Tag_DriverUninstall",
        ["驱动更新"] = "Tag_DriverUpdate",
        ["驱动配置"] = "Tag_DriverConfig",
        ["鼠标"] = "Tag_Mouse",
        ["鼠标测试"] = "Tag_MouseTest",
    };

    public static bool TryGetTagKey(string tag, out string key)
        => Tags.TryGetValue(tag, out key!);

    public static bool TryGetToolCategoryKey(string category, out string key)
        => ToolCategories.TryGetValue(category, out key!);

    public static bool TryGetBuiltinCategoryKey(string category, out string key)
        => BuiltinCategories.TryGetValue(category, out key!);
}
