using System.Collections.Generic;

namespace TubaWinUi3.Services;

/// <summary>
/// 格式转换块显示层本地化。zh 串为业务数据键（FormatParam.Label/Hint、FormatOption 名称等），
/// 显示时经 <see cref="T"/> 转换；en 下命中字典返回英文，否则原样。数据/命令/正则判定不经过此表。
/// </summary>
public static class FormatTexts
{
    /// <summary>zh→en 显示映射（仅显示层；查不到原样返回）。</summary>
    private static readonly Dictionary<string, string> EnMap = new()
    {
        [" 等 {_queue.Count} 个文件"] = " and {_queue.Count} more files",
        ["&#xE8E5; 浏览文件"] = "&#xE8E5; Browse files",
        ["0 = 不缩放，保持原分辨率"] = "0 = no scaling, keep the original resolution",
        ["0 = 不缩放；只缩小不放大"] = "0 = no scaling; shrink only, never enlarge",
        ["0 = 体积最小，10 = 质量最好（Vorbis 为可变质量编码）"] = "0 = smallest, 10 = best quality (Vorbis is a variable-quality codec)",
        ["0 = 保持原始宽度"] = "0 = keep the original width",
        ["0 = 保持原帧率"] = "0 = keep the source frame rate",
        ["0 = 保持原样；可拖动滑块，也可直接输入任意采样率（如 44100）"] = "0 = keep as is; drag the slider or type any sample rate (e.g. 44100)",
        ["0 = 原尺寸"] = "0 = original size",
        ["0 = 引擎默认"] = "0 = engine default",
        ["0 = 引擎默认；85 左右兼顾画质与体积"] = "0 = engine default; around 85 balances quality and size",
        ["0 = 引擎默认；AVIF 用较低质量即可获得好观感"] = "0 = engine default; AVIF looks good even at lower quality",
        ["0 = 引擎默认；无损模式下忽略质量"] = "0 = engine default; quality is ignored in lossless mode",
        ["0 = 最好（体积最大），9 = 最差（体积最小）"] = "0 = best (largest), 9 = worst (smallest)",
        ["0 = 最快，6 = 压缩率最高（更慢）"] = "0 = fastest, 6 = highest compression (slower)",
        ["0 = 最快，9 = 体积最小（无损，只影响耗时）"] = "0 = fastest, 9 = smallest (lossless; only affects time)",
        ["0 = 最慢最小，9 = 最快最大"] = "0 = slowest/smallest, 9 = fastest/largest",
        ["0 = 编码器默认"] = "0 = encoder default",
        ["0 = 编码器默认；可与 CRF 二选一"] = "0 = encoder default; choose either this or CRF",
        ["0 = 编码器默认；可拖动滑块，也可直接输入数值"] = "0 = encoder default; drag the slider or type a value",
        ["16 位"] = "16-bit",
        ["16 位整数"] = "16-bit integer",
        ["16 位整数（默认）"] = "16-bit integer (default)",
        ["24 位"] = "24-bit",
        ["24 位整数"] = "24-bit integer",
        ["256 色索引（体积最小）"] = "256-color indexed (smallest)",
        ["32 位"] = "32-bit",
        ["32 位整数"] = "32-bit integer",
        ["32 位浮点"] = "32-bit float",
        ["4:2:0（体积最小）"] = "4:2:0 (smallest)",
        ["4:4:4 保留彩色细节，适合截图 / 文字图"] = "4:4:4 preserves color detail; ideal for screenshots / text images",
        ["4:4:4（最清晰）"] = "4:4:4 (sharpest)",
        ["5.1 环绕"] = "5.1 surround",
        ["64 位浮点"] = "64-bit float",
        ["8 位"] = "8-bit",
        ["8 位整数"] = "8-bit integer",
        ["A-law（8 位，电话音质）"] = "A-law (8-bit, telephone quality)",
        ["AAC（默认）"] = "AAC (default)",
        ["AC-3（环绕声）"] = "AC-3 (surround)",
        ["ADPCM / 电话编码体积更小但不是无损（选择后位深无效）"] = "ADPCM / telephone codecs are smaller but not lossless (bit depth is ignored when selected)",
        ["ADPCM IMA（约 1/4 体积）"] = "ADPCM IMA (approx. 1/4 size)",
        ["ADPCM Microsoft（约 1/4 体积）"] = "ADPCM Microsoft (approx. 1/4 size)",
        ["AV1（体积最小，编码慢）"] = "AV1 (smallest, slow encoding)",
        ["Excel 表格"] = "Excel spreadsheet",
        ["FFmpeg 处理视频/音频，ImageMagick 处理图片，两者首次使用时自动下载；文档渲染引擎 OfficeCLI（单文件 33MB）负责文档真实渲染（图片/表格/复选框/页眉页脚全保留，未下载时自动回退内置引擎）；OCR 使用系统自带识别（本地完成，不联网）。"] = "FFmpeg handles video/audio and ImageMagick handles images; both auto-download on first use. The OfficeCLI document rendering engine (33MB single file) provides true document rendering (images/tables/checkboxes/headers and footers all preserved; falls back to the built-in engine when not downloaded). OCR uses the system's built-in recognition (done locally, no network).",
        ["FFmpeg 已删除，需要时可重新下载"] = "FFmpeg removed; you can download it again when needed",
        ["FLAC（无损）"] = "FLAC (lossless)",
        ["GIF 调色板模式失败，正在用简化模式重试..."] = "GIF palette mode failed, retrying with the simple mode...",
        ["H.264 / AVC（兼容性最好）"] = "H.264 / AVC (best compatibility)",
        ["H.264 / AVC（默认）"] = "H.264 / AVC (default)",
        ["H.265 / HEVC（同画质更小）"] = "H.265 / HEVC (smaller at the same quality)",
        ["HTML 引擎（内置，无需 Office）"] = "HTML engine (built-in, no Office required)",
        ["HTML 网页"] = "HTML Page",
        ["ImageMagick 已删除，需要时可重新下载"] = "ImageMagick removed; you can download it again when needed",
        ["JPEG（有损，最小）"] = "JPEG (lossy, smallest)",
        ["JPG 压缩包"] = "JPG archive",
        ["JPG 图片"] = "JPG image",
        ["JPG 质量（越大越清晰、文件越小越模糊；仅 JPG 目标生效）"] = "JPG quality (larger = sharper, smaller = blurrier and smaller file; only affects JPG targets)",
        ["JSON 数据"] = "JSON Data",
        ["LZW（无损）"] = "LZW (lossless)",
        ["MP3（默认）"] = "MP3 (default)",
        ["MP4 视频"] = "MP4 video",
        ["MPEG-4（老设备）"] = "MPEG-4 (legacy devices)",
        ["Markdown 文档"] = "Markdown Document",
        ["OCR 文本"] = "OCR text",
        ["OCR 识别 · Office / WPS"] = "OCR · Office / WPS",
        ["Office/WPS：未安装（.doc/.ppt 等旧格式不可转换）"] = "Office/WPS: not installed (legacy .doc/.ppt formats cannot be converted)",
        ["OfficeCLI · Word/Excel/PPT 真实渲染（33MB）"] = "OfficeCLI · true rendering for Word/Excel/PPT (33MB)",
        ["OfficeCLI 渲染引擎"] = "OfficeCLI rendering engine",
        ["OfficeCLI 渲染引擎已删除，需要时可重新下载"] = "OfficeCLI rendering engine removed; you can download it again when needed",
        ["Opus（高压缩）"] = "Opus (high compression)",
        ["Opus（默认，高压缩）"] = "Opus (default, high compression)",
        ["PCM 无损（按位深）"] = "PCM lossless (by bit depth)",
        ["PDF 内嵌图片的 JPEG 质量"] = "JPEG quality for images embedded in the PDF",
        ["PDF 文档"] = "PDF Document",
        ["PDF 生成失败（未产生输出文件）"] = "PDF generation failed (no output produced)",
        ["PDF合并_{DateTime.Now:yyyyMMdd_HHmmss}.pdf"] = "PDFMerge_{DateTime.Now:yyyyMMdd_HHmmss}.pdf",
        ["PDF合并_{DateTime.Now:yyyyMMdd_HHmmss}_{i}.pdf"] = "PDFMerge_{DateTime.Now:yyyyMMdd_HHmmss}_{i}.pdf",
        ["PNG 压缩包"] = "PNG archive",
        ["PNG 图片"] = "PNG image",
        ["PPT 演示"] = "PPT Presentation",
        ["TXT 文字识别"] = "TXT text recognition",
        ["TXT 文本"] = "TXT text",
        ["VBR 质量"] = "VBR quality",
        ["VP8（老设备）"] = "VP8 (legacy devices)",
        ["VP9（开源编码）"] = "VP9 (open-source codec)",
        ["VP9（默认）"] = "VP9 (default)",
        ["WMA（Windows Media 音频）"] = "WMA (Windows Media Audio)",
        ["WMV2（Windows Media 视频）"] = "WMV2 (Windows Media Video)",
        ["WebM 视频"] = "WebM video",
        ["Word 文档"] = "Word Document",
        ["Word/Excel/PPT 真实渲染组件（单文件约 33MB，镜像下载，装后完全离线）。不下载则回退内置引擎转换（保真度较低）"] = "True rendering component for Word/Excel/PPT (about 33MB single file, mirror download, fully offline once installed). Without it, conversion falls back to the built-in engine (lower fidelity)",
        ["ZIP 压缩包"] = "ZIP archive",
        ["ZIP 压缩级别（0 = 仅打包不压缩，9 = 压缩最强最慢）"] = "ZIP compression level (0 = package only, 9 = strongest and slowest)",
        ["ZIP（无损，更小）"] = "ZIP (lossless, smaller)",
        ["{_queue[0].Name} 等 {_queue.Count} 个文件"] = "{_queue[0].Name} and {_queue.Count} more files",
        ["{failedCount} 个文件失败，原因显示在文件队列中"] = "{failedCount} files failed; reasons are shown in the file queue",
        ["{name}（默认）"] = "{name} (default)",
        ["{prefix}正在转换 {item.Name}..."] = "{prefix}Converting {item.Name}...",
        ["正在转换 {item.Name}..."] = "Converting {item.Name}...",
        ["正在转换 {name}…"] = "Converting {name}…",
        ["{unsupported} 个文件无法识别格式，仍可打包为 ZIP 压缩包"] = "{unsupported} files have unrecognized formats; they can still be packed as ZIP",
        ["{zipPath}\r\n压缩前 {DownloadQueueService.FormatSize(before)} → 压缩后 {DownloadQueueService.FormatSize(after)}（节省 {saved:F1}%）"] = "{zipPath}\r\nBefore {DownloadQueueService.FormatSize(before)} → after {DownloadQueueService.FormatSize(after)} (saved {saved:F1}%)",
        ["μ-law（8 位，电话音质）"] = "μ-law (8-bit, telephone quality)",
        ["下载"] = "Download",
        ["下载中 {pct}%…"] = "Downloading {pct}%…",
        ["下载中…"] = "Downloading…",
        ["下载并继续"] = "Download and continue",
        ["不压缩"] = "None",
        ["位深"] = "Bit depth",
        ["低延迟（实时传输）"] = "Low latency (real-time)",
        ["体积明显变大，画质完全无损"] = "Clearly larger files, fully lossless quality",
        ["使用默认参数"] = "Use defaults",
        ["保持原样"] = "Keep as is",
        ["全部页"] = "All pages",
        ["关闭"] = "Off",
        ["决定无损 WAV 的码率：码率 ≈ 采样率 × 位深 × 声道"] = "Determines the bitrate of lossless WAV: bitrate ≈ sample rate × bit depth × channels",
        ["准备中..."] = "Preparing...",
        ["分辨率（最长边）"] = "Resolution (longest edge)",
        ["删除"] = "Delete",
        ["删除 EXIF / ICC 等信息，体积更小"] = "Removes EXIF / ICC and other metadata for smaller files",
        ["包含多种类别"] = "Multiple categories detected",
        ["单声道"] = "Mono",
        ["单文件约 33MB，可在下载中心查看进度"] = "About 33MB for a single file; check progress in the download center",
        ["压缩前 {DownloadQueueService.FormatSize(before)} → 压缩后 {DownloadQueueService.FormatSize(after)}"] = "Before {DownloadQueueService.FormatSize(before)} → after {DownloadQueueService.FormatSize(after)}",
        ["压缩方式"] = "Compression",
        ["压缩方法"] = "Compression method",
        ["压缩级别"] = "Compression level",
        ["原生渲染（Word / PowerPoint）"] = "Native rendering (Word / PowerPoint)",
        ["去掉音轨"] = "No audio",
        ["去除元数据"] = "Strip metadata",
        ["取消"] = "Cancel",
        ["可变质量（VBR，同体积质量更好）"] = "Variable quality (VBR, better quality at the same size)",
        ["可在下载中心查看进度"] = "Check progress in the download center",
        ["合并为一个 PDF"] = "Merge into one PDF",
        ["合并为一张长图（多页文档导出图片时纵向拼接）"] = "Merge into one tall image (vertical stitching when exporting multi-page documents as images)",
        ["合并需要两份以上 PDF"] = "Merging requires at least two PDFs",
        ["固定码率（CBR，兼容性最好）"] = "Constant bitrate (CBR, best compatibility)",
        ["图标尺寸（多选，打包进同一 .ico）"] = "Icon sizes (multi-select, packed into a single .ico)",
        ["图片"] = "Image",
        ["图片 / 视频 / 音频 / Word / Excel / PPT / PDF / Markdown / TXT / HTML / JSON&#x0a;旧版 .doc / .ppt / .wps / .et / .dps 需要本机安装 Office"] = "Images / video / audio / Word / Excel / PPT / PDF / Markdown / TXT / HTML / JSON&#x0a;Legacy .doc / .ppt / .wps / .et / .dps require Office installed",
        ["图片 · 音视频 · 文档 · 表格 · 演示 · PDF · 文本 · 任意文件打包，拖入即用"] = "Images · audio/video · documents · spreadsheets · presentations · PDF · text · pack any files — drag and drop to start",
        ["图片合并_{DateTime.Now:yyyyMMdd_HHmmss}.pdf"] = "ImageMerge_{DateTime.Now:yyyyMMdd_HHmmss}.pdf",
        ["图片合并_{DateTime.Now:yyyyMMdd_HHmmss}_{i}.pdf"] = "ImageMerge_{DateTime.Now:yyyyMMdd_HHmmss}_{i}.pdf",
        ["图片格式互转"] = "Image format conversion",
        ["图片清晰度：截图宽度（像素，越大越清晰、文件越大）"] = "Image clarity: screenshot width in pixels (larger = sharper and larger file)",
        ["图片转换与压缩引擎（约 60MB）"] = "Image conversion and compression engine (approx. 60MB)",
        ["声道"] = "Channels",
        ["处理中：{item.ProcessingStatus ?? \"处理中...\"}"] = "Processing: {item.ProcessingStatus ?? \"Processing...\"}",
        ["处理中：{item.ProcessingStatus ?? \"解压中...\"}"] = "Processing: {item.ProcessingStatus ?? \"Extracting...\"}",
        ["失败"] = "Failed",
        ["失败: {ex.Message}"] = "Failed: {ex.Message}",
        ["完成 · {outputs.Count} 个输出"] = "Done · {outputs.Count} outputs",
        ["完成 · 拆分为 {outputs.Count} 页"] = "Done · split into {outputs.Count} pages",
        ["宽度"] = "Width",
        ["导出为 ZIP 压缩包（把输出的一个或多个文件整合打包）"] = "Export as ZIP archive (pack one or more output files together)",
        ["导出选项："] = "Export options:",
        ["已删除"] = "Deleted",
        ["已加入下载队列"] = "Added to download queue",
        ["已取消"] = "Cancelled",
        ["已合并"] = "Merged",
        ["已合成 PDF"] = "PDF created",
        ["已就绪（{FfmpegService.GetFfmpegSize()}）"] = "Ready ({FfmpegService.GetFfmpegSize()})",
        ["已就绪（{MagickService.GetMagickSize()}）"] = "Ready ({MagickService.GetMagickSize()})",
        ["已就绪（{OfficeCliService.GetOfficeCliSize()}）"] = "Ready ({OfficeCliService.GetOfficeCliSize()})",
        ["已打包"] = "Packed",
        ["已打包 ZIP"] = "ZIP packed",
        ["已打包 ZIP：{zipPath}（{DownloadQueueService.FormatSize(before)} → {DownloadQueueService.FormatSize(after)}，节省 {saved:F1}%）"] = "ZIP packed: {zipPath} ({DownloadQueueService.FormatSize(before)} → {DownloadQueueService.FormatSize(after)}, saved {saved:F1}%)",
        ["已生成 {outputs.Count} 个文件"] = "{outputs.Count} files generated",
        ["已自定义："] = "Customized:",
        ["已跳过"] = "Skipped",
        ["帧率"] = "Frame rate",
        ["开启"] = "On",
        ["开始转换"] = "Start conversion",
        ["所有可转换文件"] = "All convertible files",
        ["打包完成"] = "Packing complete",
        ["打包完成（{files.Count} 个文件）"] = "Packing complete ({files.Count} files)",
        ["打开输出文件夹"] = "Open output folder",
        ["批量转换一次只处理同类文件（当前按「{CategoryName(_category)}」转换），其余文件仅可 ZIP 打包"] = "Batch conversion handles one category at a time (currently converting as \"{CategoryName(_category)}\"); other files can only be packed as ZIP",
        ["把多张图片合成为一份 PDF（按队列顺序逐页拼接）"] = "Combine multiple images into one PDF (stitched page by page in queue order)",
        ["把文件拖到这里（支持多选）"] = "Drag files here (multi-select supported)",
        ["抖动"] = "Dither",
        ["拆分为单页 PDF"] = "Split into single-page PDFs",
        ["拆分需要一份 PDF"] = "Splitting requires one PDF",
        ["指定码率"] = "Set bitrate",
        ["数值越小画质越高、体积越大"] = "Lower values mean higher quality and larger files",
        ["数值越小画质越高、体积越大（{(crfMax > 51 ? \"VP9 / AV1：0-63\" : \"H.264 / H.265：0-51\")}）；MPEG-4 / WMV2 会折算为量化器"] = "Lower values mean higher quality and larger files ({(crfMax > 51 ? \"VP9 / AV1: 0-63\" : \"H.264 / H.265: 0-51\")}); MPEG-4 / WMV2 are mapped to a quantizer",
        ["文件队列"] = "File queue",
        ["文件队列（{_queue.Count} 个 · {CategoryName(_category)}）"] = "File queue ({_queue.Count} · {CategoryName(_category)})",
        ["文本文档"] = "Text Document",
        ["文档渲染引擎"] = "Document rendering engine",
        ["无可转换格式"] = "No convertible formats",
        ["无损压缩"] = "Lossless mode",
        ["无法合并"] = "Cannot merge",
        ["无法拆分"] = "Cannot split",
        ["最长边"] = "Longest edge",
        ["未使用 OfficeCLI，将回退内置引擎转换"] = "OfficeCLI not used; falling back to the built-in engine",
        ["未安装（转换 Office 文档时自动下载，或回退内置引擎）"] = "Not installed (auto-downloads when converting Office documents, or falls back to the built-in engine)",
        ["未安装（首次使用自动下载）"] = "Not installed (auto-downloads on first use)",
        ["未知类型"] = "Unknown type",
        ["未识别到文字（图片中可能没有文字内容）"] = "No text recognized (the image may contain no text)",
        ["格式参数："] = "Format parameters:",
        ["格式转换"] = "Format Converter",
        ["检查中..."] = "Checking...",
        ["正在合并 {pdfs.Count} 份 PDF..."] = "Merging {pdfs.Count} PDFs...",
        ["正在打包 {files.Count} 个文件（压缩级别 {settings.ZipLevel}）..."] = "Packing {files.Count} files (compression level {settings.ZipLevel})...",
        ["正在把 {images.Count} 张图片合成为一份 PDF..."] = "Combining {images.Count} images into one PDF...",
        ["正在把输出打包为 ZIP..."] = "Packing outputs into ZIP...",
        ["正在拆分 {pdf.Name}..."] = "Splitting {pdf.Name}...",
        ["正在识别 {item.Name} 中的文字..."] = "Recognizing text in {item.Name}...",
        ["正在转换中"] = "Conversion in progress",
        ["没有可转换的文件"] = "No convertible files",
        ["添加文件"] = "Add files",
        ["清空"] = "Clear",
        ["渐变更平滑，但体积更大"] = "Smoother gradients, but larger files",
        ["渐进式"] = "Progressive",
        ["渲染模式（原生渲染需本机装有 Word / PowerPoint）"] = "Render mode (native rendering requires Word / PowerPoint installed)",
        ["画质 CRF"] = "Quality CRF",
        ["真彩 + 透明 RGBA"] = "Truecolor + alpha RGBA",
        ["真彩 RGB"] = "Truecolor RGB",
        ["码率"] = "Bitrate",
        ["码率 ≈ 采样率 × 位深 × 声道"] = "Bitrate ≈ sample rate × bit depth × channels",
        ["码率控制"] = "Rate control",
        ["码率模式"] = "Bitrate mode",
        ["秒"] = "seconds",
        ["立体声"] = "Stereo",
        ["等待转换"] = "Waiting",
        ["等待（仅支持 ZIP 打包）"] = "Waiting (ZIP only)",
        ["等效码率约 {EstimatePcmBitrateKbps(bits, rate, channels):0} kbps"] = "Equivalent bitrate ≈ {EstimatePcmBitrateKbps(bits, rate, channels):0} kbps",
        ["类型不匹配（仅同类批量转换或 ZIP 打包）"] = "Type mismatch (batch conversion works within one category, or pack as ZIP)",
        ["系统 OCR 可用（本地识别）"] = "System OCR available (local recognition)",
        ["系统 OCR 未装语言包"] = "System OCR language pack not installed",
        ["系统组件"] = "System components",
        ["索引色适合图标 / 截图，会损失渐变"] = "Indexed color suits icons / screenshots but loses gradients",
        ["继续转换"] = "Continue conversion",
        ["编码用途"] = "Codec application",
        ["编码速度"] = "Encoding speed",
        ["编码预设"] = "Encoding preset",
        ["网页加载时逐层显示，体积略小"] = "Displays progressively while loading; slightly smaller",
        ["自动"] = "Auto",
        ["自动（优先原生）"] = "Auto (prefer native)",
        ["自动（保持原样）"] = "Auto (keep as is)",
        ["色度采样"] = "Chroma subsampling",
        ["表格"] = "Spreadsheet",
        ["视频"] = "Video",
        ["视频 / 音频 / 图片转视频"] = "Video / audio / images to video",
        ["视频/音频转换核心组件（约 80MB）"] = "Core component for video/audio conversion (approx. 80MB)",
        ["视频时长"] = "Video duration",
        ["视频码率"] = "Video bitrate",
        ["视频编码器"] = "Video codec",
        ["该文件类型暂无可转换的目标格式"] = "No target formats available for this file type",
        ["语音（对讲，更省码率）"] = "Voice (speech, lower bitrate)",
        ["请等待当前转换完成后再添加文件"] = "Please wait for the current conversion to finish before adding files",
        ["质量"] = "Quality",
        ["质量优先（CRF，推荐）"] = "Quality first (CRF, recommended)",
        ["越大体积越小、编码越慢"] = "Higher = smaller file, slower encoding",
        ["越少体积越小；256 = 不限制"] = "Fewer colors = smaller file; 256 = no limit",
        ["越慢同画质体积越小（VP9 / AV1 折算为速度档）"] = "Slower = smaller at the same quality (mapped to speed levels for VP9 / AV1)",
        ["越高越流畅、体积越大"] = "Higher = smoother, larger file",
        ["转换中…"] = "Converting…",
        ["转换为…"] = "Convert to…",
        ["转换为…（{CategoryName(_category)}）"] = "Convert to… ({CategoryName(_category)})",
        ["转换失败"] = "Conversion failed",
        ["转换完成"] = "Conversion complete",
        ["转换完成（成功 {okCount} · 失败 {failedCount}，失败原因见队列）"] = "Conversion complete ({okCount} succeeded · {failedCount} failed; see the queue for reasons)",
        ["转换完成（成功 {okCount} 个）"] = "Conversion complete ({okCount} succeeded)",
        ["转换引擎（按需下载 / 系统组件）"] = "Conversion engines (on-demand downloads / system components)",
        ["输出："] = "Output:",
        ["输出：.txt（系统 OCR 文字识别，本地完成）"] = "Output: .txt (system OCR, done locally)",
        ["输出：.xlsx（提取 PDF 文字层中的表格；扫描版请用 OCR 文本）"] = "Output: .xlsx (extracts tables from the PDF text layer; use OCR text for scanned files)",
        ["输出：PDF合并_时间戳.pdf（把 {_queue.Count(i => i.Category == SourceCategory.Pdf)} 份 PDF 合并为一个）"] = "Output: PDFMerge_timestamp.pdf (merge {_queue.Count(i => i.Category == SourceCategory.Pdf)} PDFs into one)",
        ["输出：{Path.GetFileNameWithoutExtension(first.FullPath)}.zip（压缩级别 0-9 可调，显示压缩前后大小）"] = "Output: {Path.GetFileNameWithoutExtension(first.FullPath)}.zip (compression level 0-9 adjustable; shows before/after sizes)",
        ["输出：{Path.GetFileNameWithoutExtension(first.FullPath)}_converted.zip（内含每页 {target.Tag.ToUpperInvariant()} 图片）{notes}"] = "Output: {Path.GetFileNameWithoutExtension(first.FullPath)}_converted.zip (each page as {target.Tag.ToUpperInvariant()} image){notes}",
        ["输出：{output}{extra}{notes}"] = "Output: {output}{extra}{notes}",
        ["输出：每页一个 {Path.GetFileNameWithoutExtension(first.FullPath)}_第N页.pdf"] = "Output: one {Path.GetFileNameWithoutExtension(first.FullPath)}_pageN.pdf per page",
        ["选择目标格式："] = "Target format:",
        ["选择要转换的文件"] = "Select files to convert",
        ["部分文件类型未知"] = "Some file types are unknown",
        ["部分文件转换失败"] = "Some files failed to convert",
        ["采样率"] = "Sample rate",
        ["队列中的文件类型未知，仅可打包为 ZIP 压缩包"] = "The queue contains unknown file types; they can only be packed as ZIP",
        ["需要下载 {engineName}"] = "{engineName} download required",
        ["静态图片循环展示的时长；GIF 动图按原帧率"] = "Loop duration for still images; animated GIFs keep their frame rate",
        ["音频"] = "Audio",
        ["音频声道"] = "Audio channels",
        ["音频码率"] = "Audio bitrate",
        ["音频编码"] = "Audio codec",
        ["音频编码器"] = "Audio codec",
        ["音频采样率"] = "Audio sample rate",
        ["音频（音乐，默认）"] = "Audio (music, default)",
        ["页码范围（如 1-3,5；留空 = 全部页）"] = "Page range (e.g. 1-3,5; empty = all pages)",
        ["颜色数"] = "Colors",
        ["颜色类型"] = "Color type",
        ["首次使用需要下载：{description}。下载后离线可用，不会增加应用安装包体积。"] = "First use requires a download: {description}. It works offline afterwards and does not increase the app package size.",
        ["默认"] = "Default",
        ["默认跟随源文件；16/24 位可强制降位"] = "Default follows the source file; 16/24-bit can force a lower depth",
        ["默认（跟随源）"] = "Default (follow source)",
        ["（合并为一张长图）"] = " (merged into one tall image)",
        ["（多张图片合成一份 PDF）"] = " (multiple images combined into one PDF)",
        ["（多页文档会输出为每页一张图片）"] = " (multi-page documents output one image per page)",
        ["（导出后打包 ZIP）"] = " (packed as ZIP after export)",
        ["（旧版 doc/ppt/wps/et 可用）"] = " (legacy doc/ppt/wps/et supported)",
        ["浏览文件"] = "Browse files",
        ["（kbps）"] = " (kbps)",
        ["（px）"] = " (px)",
        ["（Hz）"] = " (Hz)",
        ["（fps）"] = " (fps)",
        ["（秒）"] = " (seconds)",
        ["所有文件"] = "All files",
        ["处理中："] = "Processing: ",
        ["解压中..."] = "Extracting...",
        ["处理中..."] = "Processing...",
        ["Office/WPS："] = "Office/WPS: ",
        ["）；MPEG-4 / WMV2 会折算为量化器"] = ") (MPEG-4 / WMV2 are mapped to a quantizer)",
        ["（VP9 / AV1：0-63）"] = " (VP9 / AV1: 0-63)",
        ["（H.264 / H.265：0-51）"] = " (H.264 / H.265: 0-51)",
        ["图片 / 视频 / 音频 / Word / Excel / PPT / PDF / Markdown / TXT / HTML / JSON\n旧版 .doc / .ppt / .wps / .et / .dps 需要本机安装 Office 或 WPS；任意文件均可打包为 ZIP"] = "Images / video / audio / Word / Excel / PPT / PDF / Markdown / TXT / HTML / JSON\nLegacy .doc / .ppt / .wps / .et / .dps require Office or WPS installed; any files can be packed as ZIP",
        ["FFmpeg 处理视频/音频，ImageMagick 处理图片，两者首次使用时自动下载；文档渲染引擎 OfficeCLI（单文件 33MB）负责文档真实渲染（图片/表格/复选框/页眉页脚全保留，未下载时自动回退内置引擎）；OCR 使用系统自带的 Windows OCR 引擎（本地识别）；旧版 Office 格式也可通过本机 Office / WPS 转换。"] = "FFmpeg handles video/audio and ImageMagick handles images; both download automatically on first use. The OfficeCLI document rendering engine (single 33MB file) provides true document rendering (images/tables/checkboxes/headers and footers preserved; falls back to the built-in engine if not downloaded). OCR uses the built-in Windows OCR engine (local recognition). Legacy Office formats can also be converted via local Office / WPS.",
        ["（{done + 1}/{totalCount}）"] = " ({done + 1}/{totalCount})",
        ["压缩前 "] = "Before ",
        [" → 压缩后 "] = " → after ",
        ["（节省 "] = " (saved ",
        ["%）"] = "%)",
        ["；"] = "; ",
        ["正在转换 {Path.GetFileName(source)}…"] = "Converting {Path.GetFileName(source)}…",
        ["OfficeCLI 渲染失败（{ex.Message}），回退内置引擎..."] = "OfficeCLI rendering failed ({ex.Message}); falling back to the built-in engine...",
        ["暂不支持的类别：{category}"] = "Category not supported yet: {category}",
        ["正在用 OfficeCLI 渲染 {Path.GetFileName(source)}…"] = "Rendering {Path.GetFileName(source)} with OfficeCLI…",
        ["正在拼接 {pagePngs.Count} 页长图..."] = "Stitching {pagePngs.Count} page(s) into one long image...",
        ["正在合成 PDF（{pagePngs.Count} 页，像素原样嵌入）..."] = "Building PDF ({pagePngs.Count} page(s), pixels embedded as-is)...",
        ["正在输出第 {i + 1}/{pagePngs.Count} 页..."] = "Writing page {i + 1}/{pagePngs.Count}...",
        ["OfficeCLI 已渲染第 {p} 页..."] = "OfficeCLI rendered page {p}...",
        ["OfficeCLI 未渲染出任何页面"] = "OfficeCLI rendered no pages",
        ["正在渲染 PDF 页面用于识别..."] = "Rendering PDF pages for recognition...",
        ["正在 OCR 识别第 {i + 1}/{pages.Count} 页..."] = "OCR page {i + 1}/{pages.Count}...",
        ["正在渲染 PDF 页面..."] = "Rendering PDF pages...",
        ["压缩包已生成（{DownloadQueueService.FormatSize(before)} → {DownloadQueueService.FormatSize(after)}）"] = "Archive created ({DownloadQueueService.FormatSize(before)} → {DownloadQueueService.FormatSize(after)})",
        ["正在提取 PDF 文字层..."] = "Extracting PDF text layer...",
        ["未检测到文字层（这是扫描版/图片型 PDF）：请改用「OCR 文本」目标进行识别"] = "No text layer found (scanned/image PDF): choose the 「OCR text」 target instead",
        ["正在生成 Excel（{totalRows} 行）..."] = "Generating Excel ({totalRows} row(s))...",
        ["正在渲染合并长图..."] = "Rendering merged long image...",
        ["RTF 中没有可提取的文字"] = "No extractable text in the RTF",
        ["内置引擎无法解析该 .et 文件，正在尝试通过 WPS / Excel 转换..."] = "The built-in engine cannot parse this .et file; trying conversion via WPS / Excel...",
        ["正在生成 XLSX..."] = "Generating XLSX...",
        ["正在解析工作簿..."] = "Parsing workbook...",
        ["表格暂不支持的目标格式：{target.Ext}"] = "Target format not supported for spreadsheets yet: {target.Ext}",
        ["JSON 内容为空"] = "JSON content is empty",
        ["不是有效的 JSON 文件：{ex.Message}"] = "Not a valid JSON file: {ex.Message}",
        ["正在生成 Word 文档..."] = "Generating Word document...",
        ["正在排版文档..."] = "Laying out document...",
        ["PDF 已生成"] = "PDF generated",
        ["正在渲染页面为图片..."] = "Rendering pages as images...",
        ["内置轻量引擎不支持 {Path.GetExtension(source)} 旧版二进制格式，且本机未安装可用的 Microsoft Office / WPS Office。"] = "The built-in lightweight engine does not support legacy binary {Path.GetExtension(source)} files, and no Microsoft Office / WPS Office is installed on this machine.",
        ["请安装 Office/WPS，或先用它们把文件另存为 .docx / .pptx / .xlsx 后再转换。"] = "Install Office/WPS, or save the file as .docx / .pptx / .xlsx in them first, then convert.",
        ["正在通过 Office / WPS 转换为{(tempExt == \".pdf\" ? \" PDF\" : tempExt.ToUpperInvariant())}中转文件..."] = "Converting via Office / WPS to a temporary{x} file...",
    };

    /// <summary>显示翻译：en 界面查表替换；zh 或未收录原样返回。动态「…（默认）」后缀自动处理。</summary>
    public static string T(string zh)
    {
        if (LocalizationService.CurrentLanguage != "en-US") return zh;
        if (EnMap.TryGetValue(zh, out var en)) return en;
        if (zh.EndsWith("（默认）"))
        {
            var head = zh[..^4];
            return (EnMap.TryGetValue(head, out var hen) ? hen : head) + " (default)";
        }
        return zh;
    }

    /// <summary>带单位的显示：en 用半角括号；zh 保持全角。</summary>
    public static string TParen(string unit) =>
        LocalizationService.CurrentLanguage == "en-US" ? " (" + T(unit) + ")" : "（" + unit + "）";

    /// <summary>运行时拼接的显示文本：模板键按 ^...$ 正则匹配（{}→捕获），普通键按长词优先子串替换。</summary>
    public static string TSub(string text)
    {
        if (LocalizationService.CurrentLanguage != "en-US" || string.IsNullOrEmpty(text)) return text;
        if (_templates.TryTranslate(text, out var translated)) return translated;
        // 含路径分隔符或换行的文本（输出路径/文件名/外部消息）不做自由子串替换，避免改写用户数据。
        if (!text.Contains('\\') && !text.Contains('\r') && !text.Contains('\n'))
        {
            foreach (var kv in _plain)
            {
                if (text.Contains(kv.Key, System.StringComparison.Ordinal))
                    text = text.Replace(kv.Key, kv.Value, System.StringComparison.Ordinal);
            }
        }
        if (text.EndsWith("（默认）", System.StringComparison.Ordinal))
            text = text[..^4] + " (default)";
        return text;
    }

    private static readonly DisplayTemplateTranslator _templates = new(EnMap);

    private static readonly System.Collections.Generic.KeyValuePair<string, string>[] _plain =
        System.Linq.Enumerable.ToArray(
            System.Linq.Enumerable.OrderByDescending(
                System.Linq.Enumerable.Where(EnMap, kv => !kv.Key.Contains('{')), kv => kv.Key.Length));

}
