namespace TubaWinUi3.Services.ToolFlows;

/// <summary>Localized guide UI with an English fallback for isolated hosts or missing resource files.</summary>
internal static class ToolFlowGoalText
{
    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["AiGoal_ReturnCurrent"] = "Back to the current step",
        ["AiGoal_OptionalAction"] = "I need this item",
        ["AiGoal_ConfirmNotice"] = "Select the requirements you have completed. This only saves your report; the app has not verified them.",
        ["AiGoal_ConfirmFallback"] = "Complete this item's configuration and access requirements in the selected plan.",
        ["AiGoal_SaveConfirmation"] = "Save my confirmation",
        ["AiGoal_RecordMissing"] = "The local plan record was removed. Return to chat and select it again.",
        ["AiDelivery_StageTools"] = "Prepare tools",
        ["AiDelivery_StageAccess"] = "Complete access setup",
        ["AiDelivery_StageRequirements"] = "Complete required preparation",
        ["AiDelivery_StageTry"] = "Ready to try",
        ["AiDelivery_SummarySelfReported"] = "Preparation includes your confirmations; actual use has not been verified.",
        ["AiDelivery_SummaryPrepared"] = "Required tools have preparation records; account access and actual use still need checking.",
        ["AiDelivery_ToolTitle"] = "Next: open your selected tool",
        ["AiDelivery_ToolHint"] = "Check account access and the model connection in the tool, then begin the first step.",
        ["AiDelivery_OpenAgent"] = "Open selected Agent",
        ["AiDelivery_OpenTool"] = "Open selected tool",
        ["AiDelivery_LocationTitle"] = "Next: open the tool location",
        ["AiDelivery_LocationHint"] = "The tool location is available. Follow the usage notes to start it and check its connection.",
        ["AiDelivery_OpenLocation"] = "Open tool location",
        ["AiDelivery_ServiceTitle"] = "Next: try your selected service",
        ["AiDelivery_ServiceHint"] = "Check sign-in and access inside the service, then try one generation or operation.",
        ["AiDelivery_OpenService"] = "Open selected service",
        ["AiDelivery_FallbackTitle"] = "Next: check your usage entry",
        ["AiDelivery_FallbackHint"] = "Preparation records are saved, but a direct entry is unavailable. Continue with the usage notes.",
        ["AiDelivery_ViewUsage"] = "View usage and handoff notes",
        ["AiDelivery_UsageDetails"] = "Usage and handoff notes",
        ["AiGoal_StagePreparing"] = "Prepare tools and access",
        ["AiGoal_StageReady"] = "Ready to try",
        ["AiGoal_SummaryPending"] = "{0} preparation steps still need attention",
        ["AiGoal_SummaryReady"] = "Required preparation steps have been handled; check the results in your project.",
        ["AiGoal_SummaryEmpty"] = "This plan has no preparation list yet.",
        ["AiGoal_AutomaticTitle"] = "Prepare {0}",
        ["AiGoal_NetworkTitle"] = "Connect {0} to the network",
        ["AiGoal_AccountTitle"] = "Sign in to {0} and check access requirements",
        ["AiGoal_SubscriptionTitle"] = "Check subscription requirements for {0}",
        ["AiGoal_ModelTitle"] = "Configure a model for {0}",
        ["AiGoal_AssetTitle"] = "Prepare assets for {0}",
        ["AiGoal_ManualTitle"] = "Set up {0}",
        ["AiGoal_AutomaticHint"] = "Check existing tools, then prepare missing items; failure details remain available.",
        ["AiGoal_ManualHint"] = "Follow the preparation notes below, check the requirements for {0}, and configure it.",
        ["AiGoal_SubscriptionHint"] = "Check the terms for {0}, then decide whether the plan requires a subscription.",
        ["AiGoal_ConfirmedHint"] = "This step is handled according to your report; the app has not verified it, and the original evidence remains in details.",
        ["AiGoal_OpenWebsite"] = "Open website",
        ["AiGoal_YourGoal"] = "Your goal: ",
        ["AiGoal_UseTitle"] = "Next: use this toolchain",
        ["AiGoal_UseHint"] = "Preparation records are saved. Open the tools, check accounts and configuration, then work toward your goal.",
        ["AiGoal_UseAction"] = "View usage steps",
        ["AiGoal_ConfirmManual"] = "I have followed these instructions",
        ["AiGoal_Problem"] = "I need help with this step",
        ["AiGoal_LaterDetails"] = "Later steps and optional tools",
        ["AiGoal_ReadyDetails"] = "Available and user-confirmed",
        ["AiGoal_EvidenceDetails"] = "View checklist and check records",
        ["AiGoal_Optional"] = "Optional",
        ["AiGoal_SelfConfirmed"] = "You confirmed this; the app has not verified your account or actual use.",
        ["AiGoal_SiteBlocked"] = "The website will not open",
        ["AiGoal_NotSignedIn"] = "Not signed in or missing access",
        ["AiGoal_NotSure"] = "I am not sure how to proceed",
        ["AiGoal_CheckAgain"] = "Check local tools again",
        ["AiGoal_SiteBlockedHint"] = "Check your network, then try the website. If it is unavailable, return to chat to choose an accessible alternative; this step stays pending.",
        ["AiGoal_NotSignedInHint"] = "Sign in on the website and check the access this plan requires. If access is missing, return to chat to change the plan; you do not need to purchase first.",
        ["AiGoal_CurrentAction"] = "Handle the current step",
        ["AiGoal_Overview"] = "View details",
        ["AiGoal_DialogTitle"] = "Continue toward your goal",
        ["AiGoal_BackToChat"] = "Back to chat",
        ["AiGoal_BrowserFailed"] = "The website did not open. Check your default browser and network.",
        ["AiGoal_ActionFailed"] = "This step could not be handled: ",
        ["AiGoal_UsageNotice"] = "Open the main tool in your plan and try a small sample. Check account access and actual operation inside the tool.",
    };

    internal static string Get(string key, string fallback) => LocalizationService.L(key,
        LocalizationService.CurrentLanguage == LocalizationService.EnglishLanguage && English.TryGetValue(key, out var value)
            ? value : fallback);
}
