namespace TubaWinUi3.Pages;

/// <summary>
/// ZXAI：AI 工具卡的辅助外链（2026-09-19）——
/// ① 官网表：卡片「🌐 官网」按钮直达官方下载页；未收录的自动回退必应搜索（永远可用）。
/// ② 一键安装表：卡片「⬇ 一键安装」按钮 → 本应用直接用 winget 装（不依赖 AI 助手/API），
///    key 对应 SystemInstaller 白名单。
/// </summary>
internal static class AiToolLinks
{
    /// <summary>名称 → 官网（尽量官方下载页；未收录自动回退搜索）。</summary>
    private static readonly Dictionary<string, string> OfficialSites = new(StringComparer.OrdinalIgnoreCase)
    {
        // ---- AI 助手 ----
        ["ChatGPT"] = "https://chatgpt.com",
        ["Claude"] = "https://claude.ai",
        ["Google Gemini"] = "https://gemini.google.com",
        ["Grok"] = "https://grok.com",
        ["DeepSeek"] = "https://chat.deepseek.com",
        ["豆包"] = "https://www.doubao.com",
        ["Kimi"] = "https://kimi.com",
        ["千问"] = "https://www.qianwen.com",
        ["文心一言"] = "https://yiyan.baidu.com",
        ["腾讯元宝"] = "https://yuanbao.tencent.com",
        ["智谱清言"] = "https://chatglm.cn",
        ["讯飞星火"] = "https://xinghuo.xfyun.cn",
        ["海螺 AI"] = "https://hailuoai.com",
        ["Perplexity"] = "https://www.perplexity.ai",
        ["秘塔 AI 搜索"] = "https://metaso.cn",
        ["纳米 AI 搜索"] = "https://www.n.cn",
        ["天工 AI"] = "https://www.tiangong.cn",
        ["NotebookLM"] = "https://notebooklm.google.com",
        ["Cherry Studio"] = "https://cherry-ai.com",
        ["ChatBox"] = "https://chatboxai.app",
        ["LobeChat"] = "https://lobehub.com",
        ["Monica"] = "https://monica.im",
        ["Sider"] = "https://sider.ai",
        ["Poe"] = "https://poe.com",
        // ---- AI agent ----
        ["Claude Code"] = "https://claude.com/claude-code",
        ["Codex"] = "https://chatgpt.com/codex",
        ["Cursor"] = "https://cursor.com",
        ["Trae"] = "https://www.trae.ai",
        ["WorkBuddy"] = "https://www.workbuddy.ai",
        ["DeepSeek Harness"] = "https://platform.deepseek.com",
        ["Windsurf"] = "https://windsurf.com",
        ["腾讯 CodeBuddy"] = "https://cloud.tencent.com/product/codebuddy",
        ["Qoder"] = "https://qoder.com",
        ["通义灵码"] = "https://tongyi.aliyun.com/lingma",
        ["豆包 MarsCode"] = "https://www.marscode.cn",
        ["GitHub Copilot"] = "https://github.com/features/copilot",
        ["Cline"] = "https://cline.bot",
        ["Roo Code"] = "https://roocode.com",
        ["Kilo Code"] = "https://kilocode.ai",
        ["Continue"] = "https://continue.dev",
        ["Aider"] = "https://aider.chat",
        ["Zed"] = "https://zed.dev",
        ["OpenClaw"] = "https://openclaw.ai",
        ["OpenCode"] = "https://opencode.ai",
        ["Lovable"] = "https://lovable.dev",
        ["Bolt.new"] = "https://bolt.new",
        ["v0"] = "https://v0.dev",
        ["Replit"] = "https://replit.com",
        ["Devin"] = "https://devin.ai",
        ["Dify"] = "https://dify.ai",
        ["n8n"] = "https://n8n.io",
        ["扣子 Coze"] = "https://www.coze.cn",
        ["Hermes"] = "https://nousresearch.com",
        ["Gemini CLI"] = "https://github.com/google-gemini/gemini-cli",
        ["Qwen Code"] = "https://github.com/QwenLM/qwen-code",
        ["iFlow CLI"] = "https://www.iflow.cn",
        ["Droid"] = "https://factory.ai",
        ["Amp"] = "https://ampcode.com",
        ["Kiro"] = "https://kiro.dev",
        ["Warp"] = "https://www.warp.dev",
        ["Goose"] = "https://github.com/aaif-goose/goose",
        ["OpenHands"] = "https://github.com/OpenHands/OpenHands",
        ["Jules"] = "https://jules.google",
        ["Manus"] = "https://manus.im",
        ["Genspark"] = "https://www.genspark.ai",
        ["FastGPT"] = "https://fastgpt.in",
        ["RAGFlow"] = "https://ragflow.io",
        ["LangFlow"] = "https://www.langflow.org",
        ["Zapier"] = "https://zapier.com",
        ["AutoGen"] = "https://github.com/microsoft/autogen",
        // ---- AI 本地部署 ----
        ["Ollama"] = "https://ollama.com",
        ["LM Studio"] = "https://lmstudio.ai",
        ["Strata"] = "https://github.com/Niko1221/Strata",
        ["vLLM"] = "https://github.com/vllm-project/vllm/releases",
        ["Jan"] = "https://jan.ai",
        ["Open WebUI"] = "https://openwebui.com",
        ["AnythingLLM"] = "https://anythingllm.com",
        // ---- AI 模型 ----
        ["DeepSeek 开放平台"] = "https://platform.deepseek.com",
        ["智谱 GLM"] = "https://open.bigmodel.cn",
        ["Kimi 开放平台"] = "https://platform.moonshot.cn",
        ["千问（Qwen）"] = "https://dashscope.aliyun.com",
        ["Jev（TypeSafe）"] = "https://typesafe.ai",
        ["LM Evaluation Harness"] = "https://github.com/EleutherAI/lm-evaluation-harness",
        ["OpenCompass 司南"] = "https://github.com/open-compass/OpenCompass",
        ["EvalScope"] = "https://github.com/modelscope/evalscope",
        ["FlagEval"] = "https://flagopen.baai.ac.cn",
        ["HELM"] = "https://github.com/stanford-crfm/helm",
        ["Inspect"] = "https://github.com/UKGovernmentBEIS/inspect_ai",
        ["DeepEval"] = "https://github.com/confident-ai/deepeval",
        ["Promptfoo"] = "https://github.com/promptfoo/promptfoo",
        ["RAGAS"] = "https://github.com/explodinggradients/ragas",
        ["Langfuse"] = "https://langfuse.com",
        ["Arize Phoenix"] = "https://github.com/Arize-ai/phoenix",
        ["Braintrust"] = "https://www.braintrust.dev",
        ["W&B Weave"] = "https://wandb.ai/site/weave",
        ["LMArena（Chatbot Arena）"] = "https://lmarena.ai",
        ["SWE-bench"] = "https://www.swebench.com",
        ["SuperCLUE"] = "https://www.superclueai.com",
        ["百度千帆（文心）"] = "https://cloud.baidu.com/product/wenxinworkshop",
        ["讯飞星火"] = "https://www.xfyun.cn",
        ["腾讯混元"] = "https://cloud.tencent.com/product/hunyuan",
        ["MiniMax 海螺"] = "https://platform.minimaxi.com",
        ["零一万物"] = "https://platform.lingyiwanwu.com",
        ["百川智能"] = "https://platform.baichuan-ai.com",
        ["阶跃星辰"] = "https://platform.stepfun.com",
        ["面壁智能"] = "https://www.modelbest.cn",
        ["硅基流动 SiliconFlow"] = "https://siliconflow.cn",
        ["OpenRouter"] = "https://openrouter.ai",
        ["OpenAI API"] = "https://platform.openai.com",
        ["Anthropic Claude API"] = "https://console.anthropic.com",
        ["Google Gemini API"] = "https://aistudio.google.com",
        ["书生·浦语 InternLM"] = "https://github.com/InternLM",
        ["天工大模型"] = "https://www.tiangong.cn",
        ["商汤日日新"] = "https://platform.sensenova.cn",
        ["豆包大模型（火山引擎）"] = "https://www.volcengine.com/product/doubao",
        ["Mistral"] = "https://mistral.ai",
        ["xAI Grok"] = "https://x.ai",
        ["Groq"] = "https://groq.com",
        ["Hugging Face"] = "https://huggingface.co",
        // ---- 软件开发 ----
        ["Visual Studio Code"] = "https://code.visualstudio.com",
        ["Node.js"] = "https://nodejs.org",
        ["Git"] = "https://git-scm.com",
        ["Python"] = "https://www.python.org",
        ["GitHub Desktop"] = "https://desktop.github.com",
        ["Windows Terminal"] = "https://aka.ms/terminal",
        ["Apifox"] = "https://apifox.com",
        ["Postman"] = "https://www.postman.com",
        ["DBeaver"] = "https://dbeaver.io",
        ["Docker Desktop"] = "https://www.docker.com",
        ["HBuilderX"] = "https://www.dcloud.io",
        ["PyCharm 社区版"] = "https://www.jetbrains.com/pycharm",
        ["IntelliJ IDEA 社区版"] = "https://www.jetbrains.com/idea",
        ["Visual Studio 社区版"] = "https://visualstudio.microsoft.com",
        ["WSL2"] = "https://aka.ms/wsl",
        ["VMware Workstation"] = "https://www.vmware.com",
        ["Wireshark"] = "https://www.wireshark.org",
        ["FileZilla"] = "https://filezilla-project.org",
        ["MobaXterm"] = "https://mobaxterm.mobatek.net",
        ["HeidiSQL"] = "https://www.heidisql.com",
        ["Sublime Text"] = "https://www.sublimetext.com",
        ["Notepad++"] = "https://notepad-plus-plus.org",
        ["Notepad--"] = "https://github.com/cxasm/notepad--",
        ["Neovim"] = "https://neovim.io",
        ["WinMerge"] = "https://winmerge.org",
        ["Fork"] = "https://git-fork.com",
        ["Sourcetree"] = "https://www.sourcetreeapp.com",
        ["JetBrains Rider"] = "https://www.jetbrains.com/rider",
        ["CLion"] = "https://www.jetbrains.com/clion",
        ["Bruno"] = "https://www.usebruno.com",
        // ---- 游戏开发 ----
        ["Godot"] = "https://godotengine.org",
        ["Blender"] = "https://www.blender.org",
        ["Unity"] = "https://unity.com",
        ["Unreal Engine"] = "https://www.unrealengine.com",
        ["Cocos Creator"] = "https://www.cocos.com",
        ["RPG Maker"] = "https://www.rpgmakerweb.com",
        ["GameMaker"] = "https://gamemaker.io",
        ["Construct 3"] = "https://www.construct.net",
        ["Aseprite"] = "https://www.aseprite.org",
        ["Pixelorama"] = "https://github.com/Orama-Interactive/Pixelorama",
        ["LibreSprite"] = "https://libresprite.github.io",
        ["Piskel"] = "https://www.piskelapp.com",
        ["Tiled"] = "https://www.mapeditor.org",
        ["Spine"] = "https://esotericsoftware.com",
        ["MagicaVoxel"] = "https://ephtracy.github.io",
        ["Blockbench"] = "https://www.blockbench.net",
        ["Material Maker"] = "https://github.com/RodZill4/material-maker",
        ["Mixamo"] = "https://www.mixamo.com",
        ["GDevelop"] = "https://gdevelop.io",
        ["Defold"] = "https://defold.com",
        ["Ren'Py"] = "https://www.renpy.org",
        ["Twine"] = "https://twinery.org",
        ["Adventure Game Studio"] = "https://www.adventuregamestudio.co.uk",
        ["Stencyl"] = "https://www.stencyl.com",
        ["Solar2D"] = "https://solar2d.com",
        ["ZBrushCoreMini"] = "https://www.maxon.net/en/zbrushcoremini",
        ["MeshLab"] = "https://www.meshlab.net",
        ["Yarn Spinner"] = "https://yarnspinner.dev",
        // ---- 办公效率 ----
        ["LibreOffice"] = "https://www.libreoffice.org",
        ["WPS Office"] = "https://www.wps.cn",
        ["Microsoft Office"] = "https://www.microsoft.com/microsoft-365",
        ["飞书"] = "https://www.feishu.cn",
        ["Notion"] = "https://www.notion.so",
        ["语雀"] = "https://www.yuque.com",
        ["Stirling PDF"] = "https://stirlingpdf.io",
        ["SumatraPDF"] = "https://www.sumatrapdfreader.org",
        ["7-Zip"] = "https://www.7-zip.org",
        ["Everything"] = "https://www.voidtools.com",
        ["Snipaste"] = "https://www.snipaste.com",
        ["Quicker"] = "https://getquicker.net",
        ["uTools"] = "https://u.tools",
        ["Obsidian"] = "https://obsidian.md",
        ["Typora"] = "https://typora.io",
        ["AutoHotkey"] = "https://www.autohotkey.com",
        ["PowerToys"] = "https://github.com/microsoft/PowerToys",
        ["XMind"] = "https://www.xmind.cn",
        ["滴答清单"] = "https://dida365.com",
        ["PotPlayer"] = "https://potplayer.daum.net",
        ["向日葵远程"] = "https://sunlogin.oray.com",
        ["Bandizip"] = "https://www.bandisoft.com",
        ["NanaZip"] = "https://github.com/M2Team/NanaZip",
        ["Ditto"] = "https://ditto-cp.sourceforge.io",
        ["幕布"] = "https://mubu.com",
        ["石墨文档"] = "https://shimo.im",
        ["ProcessOn"] = "https://www.processon.com",
        ["WizTree"] = "https://www.diskanalyzer.com",
        ["通义听悟"] = "https://tingwu.aliyun.com",
        ["讯飞听见"] = "https://www.iflyrec.com",
        ["飞书妙记"] = "https://www.feishu.cn/product/minutes",
        ["Microsoft 365 Copilot"] = "https://www.microsoft.com/microsoft-365/copilot",
        ["Gamma"] = "https://gamma.app",
        ["AiPPT"] = "https://www.aippt.cn",
        // ---- 内容创作 / 图像 ----
        ["剪映"] = "https://www.jianying.com",
        ["OBS Studio"] = "https://obsproject.com",
        ["DaVinci Resolve"] = "https://www.blackmagicdesign.com/products/davinciresolve",
        ["Kdenlive"] = "https://kdenlive.org",
        ["Canva"] = "https://www.canva.cn",
        ["Figma"] = "https://www.figma.com",
        ["GIMP"] = "https://www.gimp.org",
        ["Krita"] = "https://krita.org",
        ["Inkscape"] = "https://inkscape.org",
        ["ComfyUI"] = "https://www.comfy.org",
        ["OpenToonz"] = "https://opentoonz.github.io",
        ["Audacity"] = "https://www.audacityteam.org",
        ["Cakewalk"] = "https://www.bandlab.com/products/cakewalk",
        ["HandBrake"] = "https://handbrake.fr",
        ["创客贴"] = "https://www.chuangkit.com",
        ["Adobe Express"] = "https://www.adobe.com/express",
        ["Leonardo AI"] = "https://leonardo.ai",
        ["Ideogram"] = "https://ideogram.ai",
        ["Krea AI"] = "https://www.krea.ai",
        ["Photoshop"] = "https://www.adobe.com/products/photoshop",
        ["Paint.NET"] = "https://www.getpaint.net",
        ["Photopea"] = "https://www.photopea.com",
        ["Illustrator"] = "https://www.adobe.com/products/illustrator",
        ["Clip Studio Paint"] = "https://www.clipstudio.net",
        ["Procreate"] = "https://procreate.com",
        ["SketchBook"] = "https://sketchbook.com",
        ["SAI"] = "https://www.systemax.jp/en/sai",
        ["Stable Diffusion WebUI"] = "https://github.com/AUTOMATIC1111/stable-diffusion-webui",
        ["Midjourney"] = "https://www.midjourney.com",
        ["通义万相"] = "https://tongyi.com",
        ["即梦 AI"] = "https://jimeng.jianying.com",
        ["Affinity 系列"] = "https://affinity.serif.com",
        ["Upscayl"] = "https://upscayl.org",
        ["waifu2x"] = "https://waifu2x.udp.jp",
        ["Real-ESRGAN"] = "https://github.com/xinntao/Real-ESRGAN",
        ["Remove.bg"] = "https://www.remove.bg",
        ["MasterGo"] = "https://mastergo.com",
        ["即时设计"] = "https://js.design",
        ["Pixso"] = "https://pixso.cn",
        ["Nano Banana"] = "https://gemini.google.com",
        ["GPT Image"] = "https://chatgpt.com",
        ["Flux"] = "https://blackforestlabs.ai",
        ["文心一格"] = "https://yige.baidu.com",
        ["LiblibAI"] = "https://www.liblib.art",
        ["吐司 TusiArt"] = "https://tusiart.com",
        ["无界 AI"] = "https://www.wujieai.com",
        ["Recraft"] = "https://www.recraft.ai",
        ["稿定设计"] = "https://www.gaoding.com",
        // ---- 视频 ----
        ["CapCut"] = "https://www.capcut.com",
        ["必剪"] = "https://bcut.bilibili.cn",
        ["Premiere Pro"] = "https://www.adobe.com/products/premiere",
        ["After Effects"] = "https://www.adobe.com/products/aftereffects",
        ["Final Cut Pro"] = "https://www.apple.com/final-cut-pro",
        ["Shotcut"] = "https://www.shotcut.org",
        ["OpenShot"] = "https://www.openshot.org",
        ["ShanaEncoder"] = "https://shana.pe.kr",
        ["LosslessCut"] = "https://github.com/mifi/lossless-cut",
        ["Runway"] = "https://runwayml.com",
        ["可灵 AI"] = "https://klingai.kuaishou.com",
        ["Pika"] = "https://pika.art",
        ["HeyGen"] = "https://www.heygen.com",
        ["腾讯智影"] = "https://zenvideo.qq.com",
        ["度加剪辑"] = "https://aigc.baidu.com",
        ["D-ID"] = "https://www.d-id.com",
        ["Descript"] = "https://www.descript.com",
        ["Opus Clip"] = "https://www.opus.pro",
        ["Subtitle Edit"] = "https://www.nikse.dk/subtitleedit",
        ["Aegisub"] = "https://aegisub.org",
        ["Vrew"] = "https://vrew.voyagerx.com",
        ["Clipchamp"] = "https://clipchamp.com",
        ["威力导演"] = "https://www.cyberlink.com",
        ["会声会影"] = "https://www.videostudiopro.com",
        ["Veo"] = "https://deepmind.google/technologies/veo",
        ["Vidu"] = "https://www.vidu.studio",
        ["海螺视频"] = "https://hailuoai.com/video",
        ["智谱清影"] = "https://chatglm.cn/video",
        ["Luma Dream Machine"] = "https://lumalabs.ai",
        ["Seedance"] = "https://jimeng.jianying.com",
        ["Filmora"] = "https://filmora.wondershare.cn",
        ["万彩动画大师"] = "https://www.animiz.cn",
        // ---- 音频 ----
        ["Ocenaudio"] = "https://www.ocenaudio.com",
        ["GoldWave"] = "https://www.goldwave.com",
        ["Reaper"] = "https://www.reaper.fm",
        ["LMMS"] = "https://lmms.io",
        ["FL Studio"] = "https://www.image-line.com",
        ["Cubase"] = "https://www.steinberg.net",
        ["Studio One"] = "https://www.presonus.com",
        ["Suno"] = "https://suno.com",
        ["Udio"] = "https://www.udio.com",
        ["ElevenLabs"] = "https://elevenlabs.io",
        ["讯飞智作"] = "https://peiyin.xunfei.cn",
        ["魔音工坊"] = "https://www.moyin.com",
        ["海螺 AI 语音"] = "https://hailuoai.com/audio",
        ["Voice.ai"] = "https://voice.ai",
        ["Voicemeeter"] = "https://vb-audio.com",
        ["Adobe Audition"] = "https://www.adobe.com/products/audition",
        ["Waves"] = "https://www.waves.com",
        ["Vital"] = "https://vital.audio",
        ["Surge XT"] = "https://surge-synthesizer.github.io",
        ["Spitfire LABS"] = "https://labs.spitfireaudio.com",
        ["MuseScore"] = "https://musescore.org",
        ["MP3tag"] = "https://www.mp3tag.de",
        ["foobar2000"] = "https://www.foobar2000.org",
        ["天工 SkyMusic"] = "https://www.tiangong.cn",
        ["ACE Studio"] = "https://acestudio.ai",
        ["Riffusion"] = "https://www.riffusion.com",
        ["BandLab"] = "https://www.bandlab.com",
        // ---- 写作 / 翻译 ----
        ["秘塔写作猫"] = "https://xiezuocat.com",
        ["笔灵 AI"] = "https://ibiling.cn",
        ["彩云小梦"] = "https://if.caiyunai.com",
        ["Effie"] = "https://www.effie.pro",
        ["MarkText"] = "https://www.marktext.app",
        ["Zettlr"] = "https://www.zettlr.com",
        ["Joplin"] = "https://joplinapp.org",
        ["飞书文档"] = "https://www.feishu.cn",
        ["腾讯文档"] = "https://docs.qq.com",
        ["金山文档"] = "https://www.kdocs.cn",
        ["Grammarly"] = "https://www.grammarly.com",
        ["DeepL Write"] = "https://www.deepl.com/write",
        ["DeepL"] = "https://www.deepl.com",
        ["沉浸式翻译"] = "https://immersivetranslate.com",
        ["彩云小译"] = "https://fanyi.caiyunapp.com",
        ["有道翻译"] = "https://fanyi.youdao.com",
        ["腾讯翻译君"] = "https://fanyi.qq.com",
        ["百度翻译"] = "https://fanyi.baidu.com",
        ["Google 翻译"] = "https://translate.google.com",
        ["小牛翻译"] = "https://niutrans.com",
        ["Pot 翻译"] = "https://pot-app.com",
        ["SPlayer"] = "https://github.com/imsyy/SPlayer",
        ["微软翻译"] = "https://bing.com/translator",
        ["欧路词典"] = "https://www.eudic.net",
        ["GoldenDict"] = "https://goldendict.org",
        ["Anki"] = "https://apps.ankiweb.net",
        ["多邻国"] = "https://www.duolingo.cn",
        ["每日英语听力"] = "https://dict.eudic.net/ting",
        ["LanguageTool"] = "https://languagetool.org",
        ["Lingva Translate"] = "https://lingva.ml",
    };

    /// <summary>名称 → 一键安装 key（对应 SystemInstaller 白名单；未收录 = 无按钮）。</summary>
    private static readonly Dictionary<string, string> QuickInstall = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Cherry Studio"] = "cherry-studio",
        ["ChatBox"] = "chatbox",
        ["Jan"] = "jan",
        ["LM Studio"] = "lmstudio",
        ["Ollama"] = "ollama",
        ["Godot"] = "godot",
        ["Blender"] = "blender",
        ["GIMP"] = "gimp",
        ["Krita"] = "krita",
        ["Inkscape"] = "inkscape",
        ["OBS Studio"] = "obs",
        ["Audacity"] = "audacity",
        ["HandBrake"] = "handbrake",
        ["Kdenlive"] = "kdenlive",
        ["Shotcut"] = "shotcut",
        ["PotPlayer"] = "potplayer",
        ["Everything"] = "everything",
        ["Notepad++"] = "notepadpp",
        ["SumatraPDF"] = "sumatrapdf",
        ["LibreOffice"] = "libreoffice",
        ["WPS Office"] = "wps",
        ["Cursor"] = "cursor",
        ["Trae"] = "trae",
        ["腾讯 CodeBuddy"] = "codebuddy",
        ["Qoder"] = "qoder",
        ["Windsurf"] = "windsurf",
        ["ComfyUI"] = "comfyui",
        ["OpenShot"] = "openshot",
        ["Paint.NET"] = "paintnet",
        ["Cakewalk"] = "cakewalk",
        ["WizTree"] = "wiztree",
        ["XMind"] = "xmind",
        // —— 第三轮全量排查（2026-09-19）——
        ["Claude"] = "claude-desktop",
        ["Claude Code"] = "claude-code",
        ["Codex"] = "codex",
        ["Kimi"] = "kimi",
        ["Perplexity"] = "perplexity",
        ["Poe"] = "poe",
        ["腾讯元宝"] = "yuanbao",
        ["GitHub Desktop"] = "github-desktop",
        ["Windows Terminal"] = "windows-terminal",
        ["Devin"] = "devin",
        ["CLion"] = "clion",
        ["Bruno"] = "bruno",
        ["Fork"] = "fork",
        ["GoldenDict"] = "goldendict",
        ["Monica"] = "monica",
        ["Open WebUI"] = "open-webui",
        ["WorkBuddy"] = "workbuddy",
        ["Kiro"] = "kiro",
        ["Zed"] = "zed",
        ["Warp"] = "warp",
        ["LangFlow"] = "langflow",
        ["Replit"] = "replit",
        ["OpenCode"] = "opencode",
        ["CC Switch"] = "cc-switch",
        ["Amp"] = "amp",
        ["豆包"] = "doubao",
        ["飞书"] = "feishu-desktop",
        ["剪映"] = "jianying",
        ["必剪"] = "bcut",
        ["CapCut"] = "capcut",
        ["Figma"] = "figma",
        ["Canva"] = "canva",
        ["千问"] = "qwen-app",
        ["智谱清言"] = "chatglm",
        ["有道翻译"] = "youdao-translate",
        ["欧路词典"] = "eudic",
        ["滴答清单"] = "dida",
        ["稿定设计"] = "gaoding",
        ["讯飞听见"] = "iflyrec",
        ["语雀"] = "yuque",
        ["金山文档"] = "kdocs",
        ["幕布"] = "mubu",
        ["Anki"] = "anki",
        ["DeepL"] = "deepl",
        ["Grammarly"] = "grammarly",
        ["LanguageTool"] = "languagetool",
        ["Effie"] = "effie",
        ["MarkText"] = "marktext",
        ["Zettlr"] = "zettlr",
        ["Joplin"] = "joplin",
        ["Typora"] = "typora",
        ["Pixso"] = "pixso",
        ["MasterGo"] = "mastergo",
        ["Upscayl"] = "upscayl",
        ["waifu2x"] = "waifu2x",
        ["Clip Studio Paint"] = "clipstudio",
        ["Pixelorama"] = "pixelorama",
        ["Blockbench"] = "blockbench",
        ["Material Maker"] = "materialmaker",
        ["MeshLab"] = "meshlab",
        ["Twine"] = "twine",
        ["Ren'Py"] = "renpy",
        ["Adventure Game Studio"] = "ags",
        ["Solar2D"] = "solar2d",
        ["OpenToonz"] = "opentoonz",
        ["LosslessCut"] = "losslesscut",
        ["Subtitle Edit"] = "subtitleedit",
        ["Vrew"] = "vrew",
        ["Filmora"] = "filmora",
        ["Descript"] = "descript",
        ["SPlayer"] = "splayer",
        ["Ocenaudio"] = "ocenaudio",
        ["GoldWave"] = "goldwave",
        ["Surge XT"] = "surgext",
        ["Voicemeeter"] = "voicemeeter",
        ["ACE Studio"] = "acestudio",
        ["Snipaste"] = "snipaste",
        ["Quicker"] = "quicker",
        ["uTools"] = "utools",
        ["JetBrains Rider"] = "rider",
        ["Microsoft 365 Copilot"] = "m365copilot",
        ["Apifox"] = "apifox",
        ["PowerToys"] = "powertoys",
        ["Notion"] = "notion",
        ["Obsidian"] = "obsidian",
        ["Sublime Text"] = "sublime",
        ["Neovim"] = "neovim",
        ["DBeaver"] = "dbeaver",
        ["Postman"] = "postman",
        ["Docker Desktop"] = "docker",
        ["Wireshark"] = "wireshark",
        ["MobaXterm"] = "mobaxterm",
        ["HeidiSQL"] = "heidisql",
        ["WinMerge"] = "winmerge",
        ["Sourcetree"] = "sourcetree",
        ["Visual Studio 社区版"] = "vs-community",
        ["Unity"] = "unityhub",
        ["Unreal Engine"] = "epic",
        ["Tiled"] = "tiled",
        ["GDevelop"] = "gdevelop",
        ["LMMS"] = "lmms",
        ["MuseScore"] = "musescore",
        ["Reaper"] = "reaper",
        ["MP3tag"] = "mp3tag",
        ["foobar2000"] = "foobar2000",
        ["NanaZip"] = "nanazip",
        ["Bandizip"] = "bandizip",
        ["Ditto"] = "ditto",
        ["AutoHotkey"] = "autohotkey",
        ["Python"] = "python",
        ["Node.js"] = "node",
        ["Git"] = "git",
        ["Visual Studio Code"] = "vscode",
        ["7-Zip"] = "7zip",
        // —— ZXAI 2026-09-22：pip 类一键安装（winget 无包，官方以 pip/GitHub 分发）——
        ["vLLM"] = "vllm",
        ["Inspect"] = "inspect-ai",
        ["RAGAS"] = "ragas",
        ["HELM"] = "helm",
        ["DeepEval"] = "deepeval",
    };

    /// <summary>依赖表：一键安装前先自动检测这些依赖（缺=自动装好，已装=跳过）。用户看到的仍只是一个按钮。</summary>
    private static readonly Dictionary<string, string[]> Requires = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Docker Desktop"] = ["wsl"],
        // —— ZXAI 2026-09-22：pip 类工具（vLLM 等）需要 Python 环境 ——
        ["vLLM"] = ["python"],
        ["Inspect"] = ["python"],
        ["RAGAS"] = ["python"],
        ["HELM"] = ["python"],
        ["DeepEval"] = ["python"],
    };

    /// <summary>某工具的依赖 key 列表（无则空）。</summary>
    public static IReadOnlyList<string> RequiresOf(string name)
        => Requires.TryGetValue(name ?? "", out var r) ? r : [];

    /// <summary>官网地址：表内有=直达官网；无=自动回退必应搜索「名称 官网」（永远可用）。</summary>
    public static string OfficialUrl(string name)
        => OfficialSites.TryGetValue(name ?? "", out var url)
            ? url
            : $"https://www.bing.com/search?q={Uri.EscapeDataString((name ?? "") + " 官网下载")}";

    /// <summary>是否有可一键安装的 winget 目标。</summary>
    public static bool HasQuickInstall(string name)
        => QuickInstall.ContainsKey(name ?? "");

    /// <summary>一键安装 key（无则 null）。</summary>
    public static string? QuickInstallKey(string name)
        => QuickInstall.TryGetValue(name ?? "", out var key) ? key : null;

    /// <summary>
    /// ZXAI 2026-09-22（用户口径）：纯网页/浏览器插件类工具（无桌面客户端可装）——
    /// 卡片不显示「AI 安装」按钮、不显示「一键安装」，点卡片打开官网即为全部交互。
    /// </summary>
    private static readonly HashSet<string> WebOnly = new(StringComparer.OrdinalIgnoreCase)
    {
        "DeepSeek", "Google Gemini", "Grok", "Perplexity", "Poe",
        "秘塔 AI 搜索", "天工 AI", "海螺 AI", "NotebookLM",
        "Monica", "Sider", "Ideogram",
    };

    /// <summary>是否纯网页工具（无可安装的桌面客户端）——此类不显示「AI 安装」。</summary>
    public static bool IsWebOnly(string name) => WebOnly.Contains(name ?? "");

    /// <summary>是否显示「AI 安装」按钮（有桌面客户端才显示）。</summary>
    public static bool CanAiInstall(string name) => !IsWebOnly(name);
}
