export default {
  "app.title": "图吧工具箱CE 官方网站",
  "app.shortTitle": "图吧工具箱CE官网",
  "app.version": "1.5.6",
  "app.author": "罗澜嘎嘎",
  "app.copyright": "© 2026 罗澜嘎嘎 · 基于 GPL-3.0 协议开源",
  "app.repository": "https://github.com/luolangaga/tubatool",
  "site.slogan": "PC 硬件检测利器 · WinUI 3 原生工具箱",

  "nav.home": "首页",
  "nav.download": "下载",
  "nav.why": "为什么选择",
  "nav.docs": "文档",
  "nav.about": "关于",
  "nav.ranking": "跑分排行",
  "nav.latency": "核间延迟",
  "nav.mushroom": "毒蘑菇测试",
  "nav.theme": "主题",
  "nav.github": "在 GitHub 查看源码",

  "docs.cat-guide": "使用指南",
  "docs.cat-tools": "工具说明",
  "docs.cat-tutorials": "使用教程",
  "docs.cat-dev": "开发文档",

  "home.hero.badge": "社区重构版 · WinUI 3 原生 · 完全免费 · 开源",
  "home.hero.title": "PC 硬件检测利器",
  "home.hero.subtitle": "收录 82 款专业工具，一键启动 CPU-Z、GPU-Z、CrystalDiskMark，完全免费离线运行，零数据收集",
  "home.hero.download": "获取图吧工具箱CE",
  "home.hero.view-github": "查看 GitHub",
  "home.hero.why-choose": "为什么选择图吧工具箱CE？",
  "home.hero.license": "本项目基于 GPL-3.0 协议开源，允许自由分发。修改版须开源，禁止捆绑恶意软件。",
  "home.hero.license-link": "查看声明",
  "home.hero.store-tip": "如果你害怕下载到病毒可以到",
  "home.hero.store-name": "微软应用商店",
  "home.hero.store-tip-end": "下载",

  "home.features.title": "为电脑爱好者而生",
  "home.features.subtitle": "一站式解决硬件检测、系统维护与性能测试需求",

  "home.section1.title": "开源且完全免费",
  "home.section1.text1": "图吧工具箱CE 是原版图吧工具箱的社区重构版，免费、开源且注重隐私的 PC 硬件工具集，运行在 Windows 平台！无需使用各种不可信的网站来处理你的数据。",
  "home.section1.text2": "它自带 82 款外部工具和 20 款内置工具，包括：",
  "home.section1.items": "CPU-Z 处理器详细信息|GPU-Z 显卡参数检测|CrystalDiskMark 磁盘测速|FurMark 显卡压力测试|AIDA64 综合硬件检测",
  "home.section1.text3": "工具集是可扩展的，你可以在软件内直接提交新工具！",

  "home.section2.title": "硬件信息一目了然",
  "home.section2.text1": "图吧工具箱CE通过 WMI 实时查询处理器、主板、内存、显卡、硬盘、显示器等硬件数据，后台线程执行，不阻塞 UI。",
  "home.section2.items": "处理器型号、核心/线程数、频率|显卡型号、显存、驱动版本|内存容量、频率、插槽信息|硬盘型号、容量、健康状态|显示器分辨率、刷新率",
  "home.section2.text2": "还支持 CPU-Z 报表覆盖验证，确保数据准确可靠。",

  "home.section3.title": "WinUI 3 原生体验",
  "home.section3.text1": "图吧工具箱CE采用 WinUI 3 打造，原生拥抱 Windows 11 设计语言。",
  "home.section3.items": "Mica / Acrylic 毛玻璃背景|亮色 / 暗色 / 跟随系统主题|自定义窗口背景图片|紧凑模式 / 快速模式|全局搜索快速启动|x86 / x64 / ARM64 全架构|现代化响应式界面",

  "home.section4.title": "20 款内置实用工具",
  "home.section4.text1": "图吧工具箱CE自带 20 款内置工具，无需额外下载即可使用，覆盖系统维护的常见场景。",
  "home.section4.items": "证书屏蔽 — 阻止流氓软件证书|端口查看 — 检查活动 TCP/UDP 端口|Hosts 编辑 — 管理 hosts 映射|键盘测试 — 检测按键状态|垃圾清理 — 清理系统缓存|蓝屏分析 — 解析 BSOD 转储|更多：电池报告、网络测速、KMS 激活…",

  "home.tools.title": "82 款外部工具 + 20 款内置工具，按分类一目了然",
  "home.tools.more": "还有更多…",

  "home.support.title": "支持我们！",
  "home.support.text1": "如果你喜欢图吧工具箱CE，欢迎",
  "home.support.star": "给个 Star",
  "home.support.feedback": "提交反馈",
  "home.support.contribute": "贡献代码",
  "home.support.text2": "或提交新工具。",

  "home.footer.credit1": "网站设计灵感来源于",
  "home.footer.credit2": "界面控件基于",
  "home.footer.credit-link": "WinUIonWeb",

  "download.title": "下载图吧工具箱CE",
  "download.subtitle": "免费 · 离线运行 · 自动识别架构",
  "download.version": "最新版本",
  "download.loading": "加载中…",
  "download.detect-arch": "检测到架构：",
  "download.recommended": "推荐",
  "download.portable": "便携版",
  "download.portable-desc": "解压即用，无需安装，适合 U 盘随身携带",
  "download.lite": "精简版",
  "download.lite-badge": "仅 x64",
  "download.lite-desc": "只内置必要工具（CPU-Z / GPU-Z / HWiNFO / FurMark 等），体积更小，其余工具可在设置中升级为完整版内核",
  "download.wd-warning": "便携版可能会被 Windows Defender 误报，推荐使用安装包版，或暂时关闭 Defender 后再下载",
  "download.setup": "安装包",
  "download.setup-desc": "传统安装方式，自动创建快捷方式和开始菜单",
  "download.store": "微软商店",
  "download.store-desc": "通过官方 Microsoft Store 下载安装，自动更新",
  "download.preview": "预览版 (Preview)",
  "download.preview-desc": "直接取 GitHub / GitCode 上最新发布的构建，新改动最快拿到，也最先遇到问题",
  "download.preview-warning": "这是测试版：改动尚未经过充分验证，可能会遇到一些奇怪的问题。追求稳定请使用上面的正式版",
  "download.prerelease": "预发布",
  "download.cli": "命令行安装",
  "download.cli-desc": "使用 Windows 包管理器一键安装，自动管理更新",
  "download.winget": "Winget（Windows 自带）",
  "download.scoop": "Scoop",
  "download.gitcode": "GitCode",
  "download.gitcode-badge": "国内推荐",
  "download.now": "立即下载",
  "download.github": "GitHub",
  "download.mirror": "镜像",
  "download.cloud": "网盘下载",
  "download.cloud-sub": "全部架构",
  "download.quark": "夸克网盘",
  "download.baidu": "百度网盘",
  "download.older-title": "需要旧版本？",
  "download.gh-releases": "GitHub Releases",
  "download.gc-releases": "GitCode Releases",
  "download.sys-req": "系统要求",
  "download.sys-os": "操作系统",
  "download.sys-os-value": "Windows 10 1809+",
  "download.sys-arch": "架构",
  "download.sys-arch-value": "x64 / ARM64",
  "download.sys-runtime": "运行时",
  "download.sys-runtime-value": "无需额外安装",
  "download.sys-disk": "磁盘空间",
  "download.sys-disk-value": "约 500 MB",

  "thanks.title": "感谢下载图吧工具箱CE",
  "thanks.subtitle": "下载已开始",
  "thanks.heading": "感谢使用图吧工具箱CE！",
  "thanks.desc": "我们相信这款工具集能帮助你更好地了解自己的电脑。如果觉得好用，欢迎到 GitHub 给个项目 Star。",
  "thanks.download-started": "下载已开始",
  "thanks.download-started-desc": "浏览器已打开下载任务，文件正在传输中。",
  "thanks.type": "类型",
  "thanks.source": "来源",
  "thanks.meta-version": "你选择的版本",
  "thanks.meta-arch": "你选择的架构",
  "thanks.meta-type": "下载类型",
  "thanks.meta-source": "下载源",
  "thanks.note-title": "下载没有开始？",
  "thanks.note": "如果浏览器没有自动开始下载，请点击下方按钮重试。",
  "thanks.again": "再次下载",
  "thanks.back-home": "返回首页",

  "about.title": "关于图吧工具箱CE",
  "about.subtitle": "原版图吧工具箱的社区重构版（Community Edition）· 免费、开源、注重隐私的 PC 硬件工具集",
  "about.appearance": "外观",
  "about.theme": "主题",
  "about.theme-desc": "选择站点的显示模式",
  "about.use-system": "跟随系统",
  "about.light": "浅色",
  "about.dark": "深色",
  "about.nav-position": "导航栏位置",
  "about.nav-position-desc": "选择导航栏的显示方式",
  "about.nav-auto": "自动",
  "about.nav-left": "左侧",
  "about.nav-top": "顶部",
  "about.community": "社区与源码",
  "about.repo-desc": "欢迎 Star、反馈与贡献代码",
  "about.license": "开源协议",
  "about.license-title": "GPL-3.0 许可证",
  "about.license-desc": "本项目基于 GPL-3.0 协议开源，允许自由分发；修改版必须开源，且禁止捆绑恶意软件。",
  "about.dmca": "查看 DMCA / 恶意捆绑声明",
  "about.thanks": "特别感谢",
  "about.thanks-desc": "本站界面使用 WinUIonWeb 的 Web 版 WinUI 控件构建",
  "about.winui-on-web": "WinUIonWeb — 在网页上还原 WinUI 的项目",
  "about.open-repo": "打开代码仓库",

  "search.placeholder": "搜索文档和全站内容…",
  "search.title": "搜索",
  "search.results-for": "搜索",
  "search.results-count": "条结果",
  "search.empty-query": "输入关键词搜索文档、教程和全站内容",
  "search.no-results": "没有找到相关结果",
  "search.no-results-desc": "换个关键词试试，例如：CPU-Z、磁盘、蓝屏、硬件信息",

  "why.title": "为什么选择图吧工具箱CE？",
  "why.subtitle": "全面对比原版图吧工具箱，图吧工具箱CE在下载体验、界面设计、兼容性、功能丰富度和智能化方面全面领先",
  "why.winner": "更优",
  "why.legacy": "原版",

  "why.dl.title": "下载方式",
  "why.dl.subtitle": "多渠道高速下载 vs 仅官网单一入口",
  "why.dl.winItems": "支持 Winget 一键命令行安装|支持微软应用商店 (Microsoft Store) 安装与自动更新|支持 GitCode 国内高速下载|支持 GitHub Releases 下载|支持夸克/百度网盘下载",
  "why.dl.legacyItems": "仅支持官网下载，国内访问速度慢|无包管理器支持，无法自动更新|下载渠道单一，容易因服务器负载导致失败",

  "why.ui.title": "软件界面",
  "why.ui.subtitle": "WinUI 3 原生 Fluent Design vs 传统易语言界面",
  "why.ui.winItems": "采用 WinUI 3 框架，原生 Windows 11 设计语言|Mica / Acrylic 毛玻璃材质背景|流畅的页面切换动画与控件过渡效果|支持亮色 / 暗色 / 跟随系统主题|自定义窗口背景图片|现代化响应式布局",
  "why.ui.legacyItems": "基于易语言的传统界面，视觉效果过时|无毛玻璃材质，无动画过渡|仅支持基础暗色模式切换|界面控件样式单一",

  "why.utf8.title": "UTF-8 兼容性",
  "why.utf8.subtitle": "完美 Unicode 支持 vs 开启 UTF-8 后运行异常",
  "why.utf8.winItems": "原生支持 UTF-8 编码，路径和文件名无乱码|中文目录名（处理器工具、显卡工具等）完美显示|.NET 10 运行时原生 Unicode 处理",
  "why.utf8.legacyItems": "开启 Windows UTF-8 全局支持后运行异常|易语言默认使用 ANSI 编码，对 UTF-8 兼容性差|中文路径可能显示乱码或无法正确解析",

  "why.tools.title": "FluentUI 内置工具",
  "why.tools.subtitle": "20+ 款内置工具 vs 少量基础内置功能",
  "why.tools.winItems": "证书屏蔽 — 阻止流氓软件证书|端口查看 — 检查活动 TCP/UDP 端口|Hosts 编辑器 — 管理 hosts 映射|键盘测试 — 检测按键状态|垃圾清理 — 清理系统缓存|蓝屏分析 — 解析 BSOD 转储|网络测速、WiFi 密码查看、KMS 激活|CPU / GPU 天梯图、电池报告等",
  "why.tools.legacyItems": "内置工具数量有限|工具界面风格不统一|部分工具功能较为基础",

  "why.ai.title": "AI 智能体驱动",
  "why.ai.subtitle": "内置 AI 助手帮你解决电脑问题",
  "why.ai.winItems": "内置 AI 智能体，可回答电脑硬件和系统问题|支持多种 AI 模型接入|自然语言交互，降低使用门槛|持续迭代更新 AI 能力",
  "why.ai.legacyItems": "无 AI 功能|遇到问题需自行搜索排查",

  "why.summary.title": "图吧工具箱CE — 下一代电脑硬件检测利器",
  "why.summary.text": "从下载体验到日常使用，图吧工具箱CE在每一个维度都带来了质的飞跃。如果你还在使用原版工具箱，是时候升级了。",
  "why.summary.download": "立即下载图吧工具箱CE",

  "rank.title": "跑分排行",
  "rank.subtitle": "查看社区用户上传的性能跑分，与全球用户对比电脑性能（数据来自图吧工具箱CE社区）",
  "rank.info-title": "如何上传你的跑分？",
  "rank.info-message": "下载并安装图吧工具箱CE，运行内置的「性能测试」跑完全部项目后，点击「上传排行」即可将你的数据提交到社区排行榜。",
  "rank.sort.gaming": "游戏性能",
  "rank.sort.office": "办公性能",
  "rank.sort.cpu": "CPU 多核",
  "rank.sort.gpu": "GPU 渲染",
  "rank.sort.disk": "硬盘读取",
  "rank.sort.browser": "浏览器",
  "rank.search-placeholder": "搜索 CPU / GPU / 用户名…",
  "rank.refresh": "刷新",
  "rank.retry": "重试",
  "rank.loading": "正在加载排行榜…",
  "rank.empty": "没有符合条件的跑分记录，换个关键词试试",
  "rank.game": "游戏",
  "rank.office": "办公",
  "rank.entries": "条记录",
  "rank.page": "第",
  "rank.prev": "上一页",
  "rank.next": "下一页",
  "rank.close": "关闭",
  "rank.report-title": "的测试报告",
  "rank.detail.cpu": "CPU",
  "rank.detail.gpu": "GPU",
  "rank.detail.motherboard": "主板",
  "rank.detail.memory": "内存",
  "rank.detail.disk": "硬盘",
  "rank.detail.os": "系统",
  "rank.detail.cpu-single": "CPU 单核",
  "rank.detail.cpu-multi": "CPU 多核",
  "rank.detail.gpu-render": "GPU 渲染",
  "rank.detail.memory-cap": "内存容量",
  "rank.detail.disk-read": "硬盘顺序读",
  "rank.detail.disk-write": "硬盘顺序写",
  "rank.detail.disk-4k-read": "硬盘 4K 读",
  "rank.detail.disk-4k-write": "硬盘 4K 写",
  "rank.detail.browser": "浏览器",
  "rank.detail.submitted": "提交时间",
  "rank.detail-loading": "正在加载硬件详情…",
  "rank.detail-load-failed": "硬件详情加载失败，可稍后重试",

  "latency.title": "核间延迟查询",
  "latency.subtitle": "查看社区上传的 CPU 核间延迟热力图，对比不同处理器型号的核心间通信延迟",
  "latency.search-placeholder": "搜索 CPU / 用户名…",
  "latency.refresh": "刷新",
  "latency.retry": "重试",
  "latency.loading": "正在加载热力图列表…",
  "latency.empty": "暂无核间延迟热力图数据",
  "latency.view": "点击查看热力图",
  "latency.total": "张热力图",
  "latency.close": "关闭",
  "latency.dialog-title": "核间延迟热力图",

  "mushroom.title": "毒蘑菇测试",
  "mushroom.start": "点击开始测试"
}
